#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/001 Lil Hopper/go.ks

go.ks -- GO script for the Lil Hopper

This script manages the flight of the Lil Hopper, which is
super simple: ignite the booster, fly up and east, activate
the parachute on the way down, land safely.

NOTE: be sure to splash down in the water. We may be coming
down too fast to survive impact on solid ground.

* Import Required Packages

#+begin_src ks
  import("mp").
  import("hold").
  import("simple").
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set go to {
#+end_src

** Define Mission Phases

*** hold on pad until we have thrust, then launch

#+begin_src ks
  mpstat("Waiting for Launch").
  mphold_thrust().
  mplaunch().
#+end_src

*** pitchover during ascent until max altitude

Point the nose "surface prograde" but corrected
to be at least two degrees away from up, and
always at heading 090.

Logic unique to this vessel.

#+begin_src ks
  mpstat("Ascent").
  mpadd({ if verticalspeed <= 0 return mpinc().
    lock pitch to max(-90,min(90-2, 90-vang(up:vector,velocity:surface))).
    lock steering to heading(90,pitch,0).
    lock throttle to 1.
  return 1/10. }).
#+end_src

*** point prograde during descent until time to activate chutes

Keep the nose "surface prograde" but corrected
to be at heading 090.

#+begin_src ks
  mpstat("Descent").
  mpadd({ if altitude <= 3000 { stage. return mpinc(). }
    lock pitch to max(-90,min(90-2, 90-vang(up:vector,velocity:surface))).
    lock steering to heading(90,pitch,0).
    lock throttle to 0.
  return 1/10. }).
#+end_src

*** damp attitude rates while parachute is armed or deployed

#+begin_src ks
  mpstat("Arrival").
  mpadd({ if alt:radar <= 50 return mpinc().
    lock steering to facing.
  return 1/10. }).
#+end_src

*** push nose to vertical during final landing

#+begin_src ks
  mpstat("Landing").
  mpadd({ if verticalspeed >= 0 return mpinc().
    lock steering to heading(90,90,0).
  return 1/10. }).
#+end_src

*** tilt nose horizontal at landing

#+begin_src ks
  mpstat("Landed").
  mpadd({
    lock steering to heading(90,0,0).
  return 1. }).
#+end_src

* Run the Mission, then End the Program.

 #+begin_src ks
   mprun(). }.
#+end_src

