#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/002 Big Hopper/go.ks

go.ks -- GO script for the Big Hopper

This script manages the flight of the Big Hopper, which is
fairly simple:

* Import Required Packages

#+begin_src ks
  import("mp").
  import("hold").
  import("simple").
#+end_src

* During package import: set parameters

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set po to 89.
  set az to 270.
  set h1 to body:atm:height + 1000.
  set h2 to h1 + 1000.
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set go to {
#+end_src

** Define Mission Phases

*** hold on pad until we have thrust, then launch

#+begin_src ks
  mphold_thrust().
  mplaunch().
#+end_src

*** control pitch and heading until apoapsis is high enough

Logic unique to this vessel.

#+begin_src ks
  mpstat("Powered Ascent").
  mpadd({ if verticalspeed<=0 or apoapsis>=h2 return mpinc().
    lock steering to heading(az,po,0).
    lock throttle to max(5/100,(h2-apoapsis)/1000).
  return 1/10. }).
#+end_src

*** maintain attitude until max altitude

Logic unique to this vessel.

#+begin_src ks
  mpstat("Unpowered Ascent").
  mpadd({ if verticalspeed<=0 or altitude>=h1 return mpinc().
    lock steering to heading(az,po,0).
    lock throttle to 0.
  return 1/10. }).
  mpadd({ if altitude<70000 return mpinc().
    lock steering to heading(az,po,0).
    lock throttle to 0.
  return 1/10. }).
#+end_src

*** configure vessel for descent.

Do we need to rotate the vessel to "throw" the ascent
stage away from the capsule?

#+begin_src ks
  mpstat("Prepare for Descent").
  mpadd({ if not stage:ready return 1/10.
    lock steering to heading(az,90,0).
    lock throttle to 0.
    if vdot(steering:vector,facing:vector) > 5 return 1/10.
  stage. return 1/10. }).
#+end_src

*** control attitude during descent until chutes are safe.

#+begin_src ks
  mpstat("Descent").
  mpadd({ if altitude <= 5000 { return mpinc(). }
    lock steering to heading(az,90,0).
    lock throttle to 0.
  return 1/10. }).
#+end_src

*** Deploy Chutes.

#+begin_src ks
  mpstat("Deploy Chutes").
  mpadd({ if not stage:ready return 1/10.
    lock steering to heading(az,90,0).
    lock throttle to 0.
  stage. return mpinc(). }).
#+end_src

*** damp attitude rates while parachute is armed or deployed

#+begin_src ks
  mpstat("Prepare for Landing").
  mpadd({ if alt:radar <= 50 return mpinc().
    lock steering to facing.
    lock throttle to 0.
  return 1/10. }).
#+end_src

*** hold nose vertical during landing

#+begin_src ks
  mpstat("Landing").
  mpadd({
    if verticalspeed >= 0 mpinc().
    lock steering to heading(90,90,0).
    lock throttle to 0.
  return 1. }).
#+end_src

*** Release controls when landed.

#+begin_src ks
  mpstat("Landed").
  mpadd({
    unlock steering.
    unlock throttle.
    return 1.}).
#+end_src

* Run the Mission, then End the Program.

  #+begin_src ks
    mprun(). }.
#+end_src

