#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/006 Munar I/go.ks

go.ks -- GO script for Munar I, the first MUN Fly-By.

This script manages the flight of the 006 Munar I, which
is starting to get more complicated.

This flight is unique in that it pauses at many steps to
wait for science to be collected.

Verified on *20260621* booted from boot/local

-- did not reboot while we were LOS on the farside of mun,
   but boot/local should hold when starting imports
   until we recover signal.

* Import Required Packages

#+begin_src ks
  import("aeroperi").
  import("agl").
  import("ascent").
  import("fancystager").
  import("hold").
  import("mnpro").
  import("mp").
  import("simple").
  import("sw").
  import("time").
  import("xfer").
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set go to {
#+end_src

** Helper Functions

*** mptwp(S): add step to timewarp to S seconds before periapsis.

#+begin_src ks
  local mptwp is { parameter s.
    mppdas(). mpadd({
      local dt is eta:periapsis-s.
      return choose swadj(dt) if dt>0 else mpinc(). }).
    mpsw0(). mppdas(). }.
#+end_src

*** mptwt(): add step to timewarp to S seconds before transition.

NOTE: eta:transition is HUGE if there is no transition.

#+begin_src ks
  local mptwt is { parameter s.
    mppdas(). mpadd({
      local dt is choose eta:transition-s if orbit:hasnextpatch else 0.
      return choose swadj(dt) if dt>0 else mpinc(). }).
    mpsw0(). mppdas(). }.
#+end_src

** Start an autostager in the background

#+begin_src ks
  fancystager().
#+end_src

** Define Mission Phases

*** Collect Science on Launchpad

#+begin_src ks
  mphold_bay("Get Launchpad Science, Close Bays").
#+end_src

*** Schedule the launch.

#+begin_src ks
  mpstat("Launching Soon").
  mpone({t0put(7-mod(time:seconds,1)).}).
#+end_src

*** Get to Orbit and collect science.

#+begin_src ks
  mpcount().
  mplaunch().
  mpstat("Powered Ascent").
  mpascent(90,80000).
  mpstat("Unpowered Ascent").
  mpcoast().
  mpstat("Circularizing").
  mncirc().
  mppdas().
  mphold_brakes("Get Orbital Science, Release Brakes").
#+end_src

*** Trans-Munar injection

#+begin_src ks
  mpstat("Starting Mun Transfer").
  mpxfer("mun").
  mppdas().
#+end_src

*** Collect Science on the outbound transfer

#+begin_src ks
  mphold_brakes("Collect Outbound Science, Release Brakes").
  mpstat("Continuing to Mun SOI").
#+end_src

*** SAFEWARP to just before transition to MUN SOI

#+begin_src ks
  mptwt(60).
#+end_src

*** wait until inside MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name <> "Kerbin" return mpinc().
  return 1. }).
#+end_src

*** Collect Science inbound to Mun

#+begin_src ks
  mppdas().
  mphold_brakes("Collect Mun SOI Science, Release Brakes").
  mpstat("Continuing to Mun").
#+end_src

*** assure mun periapsis between 20 and 50 km

#+begin_src ks
  mpadd({
    if periapsis<20000 {
      lock steering to prograde.
      lock throttle to limit(0,1,(periapsis+100-40000)/1000) *
        limit(1/100,1,(10-vang(prograde:vector,facing:vector))/5).
      return 1/10.
    }
    if periapsis>50000 {
      lock steering to retrograde.
      lock throttle to limit(0,1,(periapsis+100-40000)/1000) *
        limit(1/100,1,(10-vang(retrograde:vector,facing:vector))/5).
      return 1/10.
    }
  return mpinc(). }).
  mppdas().
#+end_src

*** SAFEWARP to 120 seconds before periapsis

#+begin_src ks
  mptwp(120).
#+end_src

*** Collect Science near Mun Periapsis.

#+begin_src ks
  mphold_brakes("Collect Near-Mun Science, Release Brakes").
#+end_src

*** SAFEWARP to 60 seconds before transition out of MUN SOI

#+begin_src ks
  mpstat("Leaving Mun SOI").
  mptwt(60).
#+end_src

*** wait until out of MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name = "Kerbin" return mpinc().
    return 1. }).
  mpstat("Returning to Kerbin").
#+end_src

*** tune aerobraking target altitude.

#+begin_src ks
  mpaero().
  mppdas().
#+end_src

*** SAFEWARP to 120 km over kerbin using mnwait.

For now, using a maneuver node to mark when we want to
stop warping, rather than having to recompute it each
time through or persist it for a very few steps.

#+begin_src ks
  mpone({
    local t1 is time:seconds + 60.
    local t2 is time:seconds + eta:periapsis.
    local rx is body:radius + 120000.
    until (t2-t1)<1 {
      local t3 is t1 + (t2-t1)/2.
      local r3 is posat(t3,ship):mag.
    if r3 < rx set t2 to t3. else set t1 to t3. }
    mnclr().
    add node(t1,0,0,-1).}).

  mppdas().
  mnwait().
  mpone({ mnclr(). }).
  mppdas().
  mpstat("Aerocapture").
#+end_src

*** BURN RETROGRADE until out of fuel (when below 80 km)

It is *EXPECTED* that the auto-stager will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer
before the vessel dips below 40 km, or the apoapsis is
reduced to less than 60 km.

There is the chance that there is sufficient fuel to
really mess up the landing if the burn continues, so
once we are below 40 km or our apoapsis is below 60,
move on to the next step.

#+begin_src ks
  mpadd({
    if altitude>80000 return 1.
    if altitude<40000 and apoapsis<60000 return mpinc().
    lock steering to srfretrograde.
    lock throttle to limit(1/100,1,(10-vang(srfretrograde:vector,facing:vector))/5).
    return 1. }).
#+end_src

*** if we get here, finish configuring vessel for aerobraking.

It is *EXPECTED* that the staging to stage 0 will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer.

However, as long as the staged-away autopilot computer
is fairly close to the vessel, it will continue to run
the program, updating the display with information about
whatever chunk of debries it inhabits.

#+begin_src ks
  mpadd({ lock throttle to 0. lock steering to srfretrograde.
    if stage:number=0 mpinc().
    if stage:ready stage. return 1. }).
#+end_src

*** If we get here ... we are done.

The autopilot computer could in theory survive to this
step while remaining in close formation with the vessel.

#+begin_src ks
  mpadd({ unlock throttle. unlock steering. return mpinc(). }).
#+end_src

* Run the Mission, then End the Program.

  #+begin_src ks
    mprun(). print "program terminated".}.
#+end_src

