#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/006 Munar I/go.ks

go.ks -- GO script for Munar I, the first MUN Fly-By.

This script manages the flight of the 006 Munar One A, which
is starting to get more complicated.

This flight is unique in that it pauses at many steps to
wait for science to be collected.

Verified on *20260621* booted from boot/local

-- did not reboot while we were LOS on the farside of mun,
   but boot/local should hold when starting imports
   until we recover signal.

* Import Required Packages

#+begin_src ks
  import("hold").
  import("fancystager").
  import("simple").
  import("ascent").
  import("xfer").
  import("aeroperi").
  import("mp").
  import("sw").
  import("time").
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set go to {
#+end_src

** Start an autostager in the background

#+begin_src ks
  fancystager().
#+end_src

** Define Mission Phases

*** Collect Science on Launchpad

#+begin_src ks
  mpstat("Launchpad Science").
  mpone({bays on.}).
  mphold_bay().
#+end_src

*** Schedule the launch.

#+begin_src ks
  mpstat("Launching Soon").
  mpone({t0put(7-mod(time:seconds,1)).}).
#+end_src

*** Countdown.

#+begin_src ks
  mpcount().
#+end_src

*** launch

#+begin_src ks
  mpone({bays off.}). // just in case.
  mplaunch().
#+end_src

*** control pitch and heading until apoapsis is high enough

#+begin_src ks
  mpstat("Powered Ascent").
  mpascent(90,80000).
#+end_src

*** coast until above atmosphere.

#+begin_src ks
  mpstat("Unpowered Ascent").
  mpcoast().
#+end_src

*** circularize at apoapsis.

#+begin_src ks
  mpstat("Circularizing").
  mpcirc().
#+end_src

*** Collect Science on Orbit

#+begin_src ks
  mpstat("Orbital Science").
  mppdas(). mphold_bay(). mppdas().
#+end_src

*** Trans-Munar injection

#+begin_src ks
  mpxfer("mun").
#+end_src

*** WAIT HERE until ready to continue.

#+begin_src ks
  mppdas(). mppdas(). mppdas().
#+end_src

*** SAFEWARP to just before transition to MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    local dt is eta:transition-60.
    if dt<=0 return mpinc().
  swadj(dt). return 1/10. }).
  mpadd(swend).
#+end_src

*** wait until inside MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name <> "Kerbin" return mpinc().
  return 1. }).
#+end_src

*** WAIT HERE until ready to continue.

#+begin_src ks
  mppdas(). mppdas(). mppdas().
#+end_src

*** assure mun periapsis between 20 and 50 km

#+begin_src ks
  mpadd({
    if periapsis<20000 {
      lock steering to prograde.
      lock throttle to limit(0,1,(periapsis+100-40000)/1000) *
        limit(1/100,1,(10-vang(prograde:vector,facing:vector))/5).
      return 1/10.
    }
    if periapsis>50000 {
      lock steering to retrograde.
      lock throttle to limit(0,1,(periapsis+100-40000)/1000) *
        limit(1/100,1,(10-vang(retrograde:vector,facing:vector))/5).
      return 1/10.
    }
  return mpinc(). }).
  mppdas(). mppdas(). mppdas().
#+end_src

*** SAFEWARP to a bit before periapsis

#+begin_src ks
  mpadd({ if eta:periapsis<60 return mpinc().
    local dt is eta:periapsis-120.
    if dt<=0 return mpinc().
  swadj(dt). return 1/10. }).
  mpadd(swend).
#+end_src

*** WAIT HERE until ready to continue.

#+begin_src ks
  mppdas(). mppdas(). mppdas().
#+end_src

*** SAFEWARP to just before transition out of MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    local dt is eta:transition-60.
    if dt<=0 return mpinc().
  swadj(dt). return 1/10. }).
  mpadd(swend).
#+end_src

*** wait until out of MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name = "Kerbin" return mpinc().
  return 1. }).
#+end_src

*** tune aerobraking target altitude.

#+begin_src ks
  mpadd(aeroperi).
  mppdas(). mppdas(). mppdas().
#+end_src

*** SAFEWARP to 120 km over kerbin using mnwait.

#+begin_src ks
  mpone({
    local t1 is time:seconds + 60.
    local t2 is time:seconds + eta:periapsis.
    local rx is body:radius + 120000.
    until (t2-t1)<1 {
      local t3 is t1 + (t2-t1)/2.
      local r3 is posat(t3,ship):mag.
    if r3 < rx set t2 to t3. else set t1 to t3. }
    mnclr().
  add node(t1,0,0,-1).}).
  mnwait().
  mpone({ mnclr(). }).
    mppdas().
#+end_src

*** BURN RETROGRADE until out of fuel (when below 80 km)

It is *EXPECTED* that the auto-stager will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer.

#+begin_src ks
  mpadd({
    if altitude>80000 return 1.
    if altitude<40000 and apoapsis<60000 return mpinc().
    lock steering to srfretrograde.
    lock throttle to limit(1/100,1,(10-vang(srfretrograde:vector,facing:vector))/5).
  return 1. }).
#+end_src

*** if we get here, finish configuring vessel for aerobraking.

It is *EXPECTED* that the staging to stage 0 will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer.

#+begin_src ks
  mpadd({ lock throttle to 0. lock steering to srfretrograde.
    if stage:number=0 mpinc().
  if stage:ready stage. return 1. }).
#+end_src

*** If we get here ... we are done.

Congratulations. Your autopilot was adding mass to the
part of the vehicle that floated down on the parachute.

#+begin_src ks
  mpadd({ unlock throttle. unlock steering. return mpinc(). }).
#+end_src

* Run the Mission, then End the Program.

  #+begin_src ks
    mprun(). print "program terminated".}.
#+end_src

