#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/008 Munar II/go.ks

go.ks -- GO script for Munar II, the first MUN Lande

This script manages the flight of the 006 Munar II, which
is amazingly cool.

This flight is unique in that it lands on Mun, then returns
to safe aerobraking on Kerbin.

This script uses "local.ks" to save onboard storage. Rebooting
when there is no connection causes the boot loader to pause,
which is OK when we are in Mun orbit awaiting landing, or on
Mun awaiting launch.

Budget for Lander: 1210 m/s
Available in 008 Munar II lander: 1391 m/s
reserve the excess for return corrections

|  ΔV | Leg                     |
|-----+-------------------------|
|   0 | Aerocapture             |
| 280 | 14x14 to Mun Escape     |
| 730 | Mun Surface to 14x14    |
| 200 | Lander share of Landing |

Budget for Orbiter: 2810 m/s
Budget for Orbiter+Lander: 4020 m/s
Available in 008 Munar II orbiter excluding lander: 1391 m/s
reserve the excess for return corrections

|   ΔV | Leg                     |
|------+-------------------------|
| -200 | Lander share of landing |
|  870 | land on mun             |
|  280 | enter 14x14 orbit       |
|  860 | intercept mun           |
| 1000 | Orbiter share of LKO    |

Booster: needs to suipply 2800 m/s
for the 3800 m/s launch-to-LKO,
Mission Budget: 6820 m/s

TEST FLIGHTS:

- lander itself is able to launch
  from mun and return to kerbin,
  with sufficient margin to cover
  200 m/s of the landing plus more
  than enough for aero.

- full configuration, Vacuum ΔV:

  6947 m/s available in VAB
  3729 m/s available at Kerbin 80x80
  2858 m/s available during Transfer to Mun
  2514 m/s available at Mun 14x14

  Suggestion: schedule a 670 m/s retrograde
  burn from mun orbit. when complete,
  jettison stage 3 to free stage 2 for
  use for landing and return.

Landing Dev Configuration:

- discard everything below stage 3

- requires that we jettison stage 3
  well before the final landing.

- AltF12 menu claims 15.25 km is the
  minimum safe orbit around Mun.

- budget says that on orbit we need 1880 m/s

* Import Required Packages

#+begin_src ks
  import("aeroperi").
  import("agl").
  import("ascent").
  import("escape").
  import("fancystager").
  import("hold").
  import("mnpro").
  import("mp").
  import("simple").
  import("sw").
  import("time").
  import("xfer").
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set go to {
#+end_src

** Helper Functions

*** mptwp(S): add step to timewarp to S seconds before periapsis.

#+begin_src ks
  local mptwp is { parameter s.
    mppdas(). mpadd({
      local dt is eta:periapsis-s.
      return choose swadj(dt) if dt>0 else mpinc(). }).
    mpsw0(). mppdas(). }.
#+end_src

*** mptwt(): add step to timewarp to S seconds before transition.

NOTE: eta:transition is HUGE if there is no transition.

#+begin_src ks
  local mptwt is { parameter s.
    mppdas(). mpadd({
      local dt is choose eta:transition-s if orbit:hasnextpatch else 0.
      return choose swadj(dt) if dt>0 else mpinc(). }).
    mpsw0(). mppdas(). }.
#+end_src

** Start an autostager in the background

#+begin_src ks
  fancystager().
#+end_src

** Define Mission Phases

*** Schedule the launch.

#+begin_src ks
  mpstat("Launching Soon").
  mpone({t0put(7-mod(time:seconds,1)).}).
  mpone({bays off.}).    
#+end_src

*** Get to initial Low Kerbin Orbit.

#+begin_src ks
  mpcount().
  mplaunch().
  mpstat("Powered Ascent").
  mpascent(90,80000).
  mpstat("Unpowered Ascent").
  mpcoast().
  mpstat("Circularizing").
  mpcirc().
  mppdas().
#+end_src

*** Trans-Munar injection

#+begin_src ks
  mpstat("Starting Mun Transfer").
  mpxfer("mun").
  mppdas().
#+end_src

*** SAFEWARP to just before transition to MUN SOI

#+begin_src ks
  mpstat("Transfer Orbit to MUN SOI").
  mptwt(60).
#+end_src

*** wait until inside MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name <> "Kerbin" return mpinc().
  return 1. }).
  mppdas().
#+end_src

*** assure mun periapsis between 13 and 15 km

Mission behavior so far is expected to result
in a free return trajectory ending in a safe
aerobraking maneuver at Kerbin. On the way it
is planned to pass about 40 km from Mun.

Do a correction burn here to move the periapsis
down to 10 km. Assure it behaves properly when
the periapsis happens to already be too low.

#+begin_src ks
  mpstat("Refining MUN Approach").
  mpadd({
    if periapsis<(10000-200) {
      lock steering to prograde.
      lock throttle to limit(0,1,(10000-periapsis)/1000) *
        limit(1/100,1,(10-vang(prograde:vector,facing:vector))/5).
      return eps.
    }
    if periapsis>(10000+200) {
      lock steering to retrograde.
      lock throttle to limit(0,1,(periapsis-10000)/1000) *
        limit(1/100,1,(10-vang(retrograde:vector,facing:vector))/5).
      return eps.
    }
    lock throttle to 0. return mpinc(). }).
  mppdas().
#+end_src

*** Circularize at periapsis.

#+begin_src ks
  mpstat("Entering MUN Orbit").
  mpcirc().
  mppdas().
#+end_src

*** DEVELOPMENT CHECKPOINT

Delta V available on 008 Munar II:

Note that Stage 3 has 1123 m/s available,
but 870 gets us to landing, and we do NOT
want to land on the poodle, do we?

Perhaps, plan a 670 m/s retrograde burn,
then stage away the poodle so we can land
using the lander.

#+begin_src ks
  mpsw0().
  mppdas().
  mphold_brakes("Release Brakes to Test").
#+end_src

*** TODO deorbit toward mun

Burn retrograde at the top.

Cancel horizontal velocity over landing site.

Descend at planned acceleration to zero.
- given height and speed, compute exact
  acceleration necessary to stop at zero.
- start burning when it exceeds 90% throttle
- once stated, keep burning until done.
- throttle up and down as needed

#+begin_src ks
  local land_log_file is home:combine("landing.log").
  if exists(land_log_file) open(land_log_file):clear().
  function land_log { parameter m. log TEE()+m to land_log_file.}
  land_log(" Rebooted into landing test").

  mpadd({
  }).

  mpadd({
  }).
#+end_src

*** TODO mun descent 

*** TODO mun landing

*** hold on mun until done

#+begin_src ks
  mphold_brakes("Release Brakes to Leave MUN").
#+end_src

*** Leave Mun

Launching to 270. The method I use to find my
return trajectory fails when launching to 090.

Going via a 14x14 orbit uses less fuel than going
via the 40x40 orbit. 10x10 is even slightly less.

#+begin_src ks
  mpstat("Leaving Mun").
  mpadd({lock steering to heading(270,90,0). lock throttle to 1.
    if agl()<50 return 1/10.
    gear off. lights on. return mpinc().}).
  mpstat("Powered Ascent").
  mpascent(270,10000).
  mpstat("Unpowered Ascent").
  mpcoast().
  mpstat("Circularizing").
  mpcirc().
  mppdas().
#+end_src

*** escape from MUN orbit

#+begin_src ks
  mpstat("Leaving MUN Orbit").
  mpescape().
#+end_src

*** SAFEWARP to 60 seconds before transition out of MUN SOI

#+begin_src ks
  mpstat("Leaving Mun SOI").
  mptwt(60).
#+end_src

*** wait until out of MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name = "Kerbin" return mpinc().
    return 1. }).
  mpstat("Returning to Kerbin").
#+end_src

*** tune aerobraking target altitude.

#+begin_src ks
  mpaero().
  mppdas().
#+end_src

*** SAFEWARP to 120 km over kerbin using mnwait.

For now, using a maneuver node to mark when we want to
stop warping, rather than having to recompute it each
time through or persist it for a very few steps.

#+begin_src ks
  mpone({
    local t1 is time:seconds + 60.
    local t2 is time:seconds + eta:periapsis.
    local rx is body:radius + 120000.
    until (t2-t1)<1 {
      local t3 is t1 + (t2-t1)/2.
      local r3 is posat(t3,ship):mag.
    if r3 < rx set t2 to t3. else set t1 to t3. }
    mnclr().
    add node(t1,0,0,-1).}).

  mppdas().
  mnwait().
  mpone({ mnclr(). }).
  mppdas().
  mpstat("Aerocapture").
#+end_src

*** BURN RETROGRADE until out of fuel (when below 80 km)

It is *EXPECTED* that the auto-stager will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer
before the vessel dips below 40 km, or the apoapsis is
reduced to less than 60 km.

There is the chance that there is sufficient fuel to
really mess up the landing if the burn continues, so
once we are below 40 km or our apoapsis is below 60,
move on to the next step.

#+begin_src ks
  mpadd({
    if altitude>80000 return 1.
    if altitude<40000 and apoapsis<60000 return mpinc().
    lock steering to srfretrograde.
    lock throttle to limit(1/100,1,(10-vang(srfretrograde:vector,facing:vector))/5).
    return 1. }).
#+end_src

*** if we get here, finish configuring vessel for aerobraking.

It is *EXPECTED* that the staging to stage 0 will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer.

However, as long as the staged-away autopilot computer
is fairly close to the vessel, it will continue to run
the program, updating the display with information about
whatever chunk of debries it inhabits.

#+begin_src ks
  mpadd({ lock throttle to 0. lock steering to srfretrograde.
    if stage:number=0 mpinc().
    if stage:ready stage. return 1. }).
#+end_src

*** If we get here ... we are done.

The autopilot computer could in theory survive to this
step while remaining in close formation with the vessel.

#+begin_src ks
  mpadd({ unlock throttle. unlock steering. return mpinc(). }).
#+end_src

*** DEVELOPMENT HACK: pause, await abort, reboot

#+begin_src ks
  mpstat("Test Done, ABORT to reboot").
  mpone({abort off. wait until abort. abort off. reboot.}).
#+end_src

* Run the Mission, then End the Program.

  #+begin_src ks
    mprun(). print "program terminated".}.
#+end_src

