#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/008 Mun Lander I/go.ks

go.ks -- GO script for Mun Lander I, the first MUN LANDER

This script manages the flight of the 008 Mun Lander I, which
is an extremely significiant mission.

* Mission Budgetg

** 2810 m/s for Orbiter (total 4020)

| Segment                | Map | Mike |
|------------------------+-----+------|
| Upper Insertion        |     | 1000 |
| Mun Transfer           | 280 |  860 |
| Mun Capture            | 580 |  280 |
| Mun Landing            |     |  870 |
| Lander part of landing |     | -200 |

** 1210 m/s for Lander

| Segment                 | Map | Mike |
|-------------------------+-----+------|
| Lander part of landing  |     |  200 |
| Mun to 14x14            | 580 |  730 |
| 14x14 to escape to aero | 280 |  280 |

* Import Required Packages

Our required packages do not fit in 10000 bytes.

#+begin_src ks
  import("aeroperi").
  import("ascent").
  import("escape").
  import("fancystager").
  import("fmt").
  import("hud").
  import("mp").
  import("mnpro").
  import("sw").
  import("time").
  import("xfer").
#+end_src

* During package import: parameters and helper functions

* Local mission steps and helper functions

** pdas -- Point Down At Sun

#+begin_src ks
  local pdas is {
    local h is vcrs(body:position,ship:velocity:orbit).
    lock throttle to 0.
    lock steering to lookdirup(h,-sun:position).
    BAYS ON.
    local a is vang(facing:upvector,sun:position).
    if a>175 mpinc(). return 1. }.
#+end_src

** hold -- Wait until bay is closed.

#+begin_src ks
  local hold is { if not bays mpinc().
  hud("BAY "+(choose "OPEN" if BAYS else "OK"), false). return 2. }.
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set futurego to {
#+end_src

** Start an autostager in the background

#+begin_src ks
  fancystager().
#+end_src

** Define Mission Phases

*** Schedule the launch.

#+begin_src ks
  mpone({t0put(7-mod(time:seconds,1)).}).
#+end_src

*** Countdown.

#+begin_src ks
  mpadd({
    local t is -met().
    local d is round(t).
    if d<=1 mpinc().
    if d<=5 hud("...").
    return t-round(t-1).}).
#+end_src

*** Ignite the engines.

#+begin_src ks
  mpone({
    if availablethrust>0 return mpinc().
    if not stage:ready return 1/10.
    lock throttle to 1.
    lock steering to facing.
    hud("ignition"). stage. t0put(0).}).
#+end_src

*** damp attitude rate until safe to maneuver

#+begin_src ks
  mpadd({ if alt:radar>=50 return mpinc().
    lock throttle to 1.
    lock steering to facing.
    bays off.
  return 1/10. }).
  mpone({hud("pitchover").}).
#+end_src

*** control pitch and heading until apoapsis is high enough

#+begin_src ks
  mpadd(ascent(90,80000)).
  mpone({lock throttle to 0. hud("MECO").}).
#+end_src

*** coast until above atmosphere.

#+begin_src ks
  mpadd({ if altitude>body:atm:height return mpinc().
    lock steering to prograde. lock throttle to 0. return 1. }).
  mpone({hud("SPACE!").}).
#+end_src

*** circularize at apoapsis.

#+begin_src ks
  mncirc().
  mpone({hud("ORBIT!").}).
  mppdas().
#+end_src

*** trans-munar injection

#+begin_src ks
  mpone({hud("Trans-Munar Injection").}).
  mpxfer("mun").
  mpone({hud("Trans-Munar Trajectory Established").}).
  mppdas().
#+end_src

*** SAFEWARP to just before transition to MUN SOI

#+begin_src ks
  mpadd({swadj(choose eta:transition-60 if orbit:hasnextpatch else 0).
    return choose mpinc() if wfnow()=1 else 1/10.}).
  mppdas().
#+end_src

*** wait until inside MUN SOI

#+begin_src ks
  mpadd({
    if not orbit:hasnextpatch return mpinc().
    if body:name <> "Kerbin" return mpinc().
    return 1. }).
  mpone({hud("Entering MUN SOI").}).
  mppdas().
#+end_src

*** Assure MUN periapsis between 12 and 16 km.

#+begin_src ks
  mpadd({
    if periapsis<12000 {
      lock steering to prograde.
      lock throttle to limit(0,1,(14000-periapsis-100)/1000) *
        limit(1/100,1,(10-vang(prograde:vector,facing:vector))/5).
      return 1/10.}
    if periapsis>16000 {
      lock steering to retrograde.
      lock throttle to limit(0,1,(periapsis+100-14000)/1000) *
        limit(1/100,1,(10-vang(retrograde:vector,facing:vector))/5).
      return 1/10.}
  return mpinc(). }).
  mppdas().
#+end_src

*** Schedule circularization at MUN periapsis.

#+begin_src ks
  mncirc().
  mppdas().
  mpone({hud("MUN Orbit").}).
#+end_src

*** TODO pick a landing location

*** TODO deorbit and land

*** TODO hold on the ground until ready to leave

*** TESTING SUPPORT for "start on mun"

IDEA: get the end of the mission working,
then work backward toward "what do we need
to do to get to where the rest of the mission
can happen" ...

Currently: start on the surface of Mun, and
get the "launch, escape, return, aero" part
of the mission working.

We have the "from Mun 14x14 to Aero" part
working from Munar Ib.

#+begin_src ks
  mpl:clear().
#+end_src

#+begin_src ks
  mpadd({
    if availablethrust>0 return mpinc().
    lock throttle to 0.
    hud("Activate Engines to Leave.").
  }).
#+end_src

*** launch from mun into 14x14 orbit

  #+begin_src ks
  mpadd(ascent(90,14000)).
  mpone({lock throttle to 0. hud("MECO").}).
  mncirc().
  mpone({hud("ORBIT!").}).
  mppdas().
#+end_src

*** escape from MUN orbit

This sequence was used previously from a
retrograde orbit around mun, where we depart
over the backside.

This mission could have any inclination.

#+begin_src ks
  mpone({hud("Planning MUN Escape").}).
  mpadd(escape).
  mppdas().
  mnwait().
  mpone({hud("Leaving MUN Orbit").}).
  mnexec().
  mnfini().
#+end_src

*** SAFEWARP to just before transition out of MUN SOI

#+begin_src ks
  mpadd({swadj(choose eta:transition-60 if orbit:hasnextpatch else 0).
    return choose mpinc() if wfnow()=1 else 1/10.}).
  mppdas().
#+end_src

*** wait until out of MUN SOI

#+begin_src ks
  mpadd({ if not orbit:hasnextpatch return mpinc().
    if body:name = "Kerbin" return mpinc().
    return 1. }).
  mpone({hud("Returning to KERBIN").}).
#+end_src

*** tune aerobraking target altitude.

#+begin_src ks
  mpadd(aeroperi).
  mppdas().
#+end_src

*** SAFEWARP to 120 km over kerbin using mnwait.

#+begin_src ks
  mpone({
    local t1 is time:seconds + 60.
    local t2 is time:seconds + eta:periapsis.
    local rx is body:radius + 120000.
    until (t2-t1)<1 {
      local t3 is t1 + (t2-t1)/2.
      local r3 is posat(t3,ship):mag.
    if r3 < rx set t2 to t3. else set t1 to t3. }
    mnclr().
  add node(t1,0,0,-1).}).
  mnwait().
  mpone({hud("Ready for AEROBRAKING").}).
  mpone({ mnclr(). }).
  mppdas().
#+end_src

*** BURN RETROGRADE until out of fuel (when below 80 km)

It is *EXPECTED* that the auto-stager will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer.

#+begin_src ks
  mpadd({
    if altitude>80000 return 1.
    if altitude<40000 and apoapsis<60000 return mpinc().
    lock steering to srfretrograde.
    lock throttle to limit(1/100,1,(10-vang(srfretrograde:vector,facing:vector))/5).
  return 1. }).
#+end_src

*** if we get here, finish configuring vessel for aerobraking.

It is *EXPECTED* that the staging to stage 0 will stage away
the flamed-out engine, empty fuel tank, science cluster,
probe core, battery, solar panel, and autopilot computer.

#+begin_src ks
  mpone({hud("Final Stage Separation").}).
  mpadd({ lock throttle to 0. lock steering to srfretrograde.
    if stage:number=0 mpinc().
  if stage:ready stage. return 1. }).
#+end_src

*** If we get here ... we are done.

Congratulations. Your autopilot was adding mass to the
part of the vehicle that floated down on the parachute.

#+begin_src ks
  mpone({hud("What CPU is running this code?").}).
  mpadd({ unlock throttle. unlock steering. return mpinc(). }).
  mpone({hud("Falling Off the Bottom").}).
#+end_src

* Run the Mission, then End the Program.

  #+begin_src ks
    mprun(). HUD("program terminated").}.
#+end_src

