#!/bin/bash -
sscr="$0"
self=$(basename "$sscr" .sh)
sdir=$(cd "$(dirname "$sscr")"; env PWD= /bin/pwd)
cd "$sdir"
for org in *.org
do
   base=${org%.org}
   ks="../../Archive/home/${base}/go.ks"
   if [ ! -e "$ks" ] || [ "$ks" -ot "$org" ]; then
     printf '== tangle %s\n' "$org"
     python ../../bin/tangle.py "$org"
   fi
done
contracts/update
