go.ks -- GO script for the Kemini Ib aka Polar Express

This script manages the flight of the Kemini Ib, which is
less simple.

* Import Required Packages

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  import("mp").
  import("fancystager").
  import("ascent").
  import("simplecirc").
#+end_src

* During package import: set parameters

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  set go to {
#+end_src

** debug helper for "next stage"

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  set msgnext to { parameter s. print s. return mpinc(). }.
#+end_src

** Start an autostager in the background

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  fancystager().
#+end_src

** Define Mission Phases

*** prompt the flight engineer to initiate the flight.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpone({print "Activate engines when ready.".}).
#+end_src

*** hold on pad until we have thrust.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if maxthrust>0 return mpinc().
  return 1/10. }).
#+end_src

*** damp attitude rate until safe to maneuver

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if alt:radar>=50 return mpinc().
    lock throttle to 1.
    lock steering to facing.
  return 1/10. }).
#+end_src

*** control pitch and heading until apoapsis is high enough

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd(ascent(355,72000)).
#+end_src

*** coast until above atmosphere.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if altitude>body:atm:height return mpinc().
    lock steering to prograde. lock throttle to 0.
  return 1. }).
#+end_src

*** circularize at apoapsis.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd(simplecirc).
#+end_src

*** gather science in orbit.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpone({ brakes on. print "Release brakes to land.". }).
    mpadd({ if not brakes return mpinc().
      lock throttle to 0.
      lock steering to vcrs(body:position,ship:velocity:orbit).
      return 1.
    }).
#+end_src

*** drop periapsis to half atmosphere height.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if periapsis<40000 return mpinc().
    lock steering to retrograde.
    lock throttle to max(0,min(1,(periapsis+100-40000)/1000)) *
    max(1/100,min(1,(10-vang(retrograde:vector,facing:vector))/5)).}).
#+end_src

*** configure vessel for re-entry.

Stage ONCE to jettison the orbital maneuvering engines.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({
    lock throttle to 0.
    lock steering to vcrs(body:position,ship:velocity:orbit).
    if altitude>body:atm:height return 1/10.
    if not stage:ready return 1/10.
    if vdot(north:vector,facing:vector) > 5 return 1/10.
  stage. return mpinc(). }).
#+end_src

*** control attitude during descent until chutes are safe.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if altitude <= 5000 { return mpinc(). }
    lock steering to srfretrograde.
  return 1/10. }).
#+end_src

*** Deploy Chutes.

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if not stage:ready return 1/10.
    lock steering to heading(90,90,0).
  stage. return mpinc(). }).
#+end_src

*** damp attitude rates while parachute is armed or deployed

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({ if alt:radar <= 50 return mpinc().
    lock steering to facing.
  return 1/10. }).
#+end_src

*** hold nose vertical during and after landing

#+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
  mpadd({
    lock steering to heading(90,90,0).
  return 1. }).
#+end_src

* Run the Mission, then End the Program.

 #+begin_src ks :results none :tangle ../Archive/home/003 Kemini Ib/go.ks
   mprun(). print "program terminated".}.
#+end_src

