go.ks -- GO script for Kemini I/C aka The Space Taxi

This script manages the flight of the Kemini I/C, which is
less simple.

* Import Required Packages

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  import("mp").
  import("fancystager").
  import("ascent").
  import("simplecirc").
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  set go to {
#+end_src

** Start an autostager in the background

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  fancystager().
#+end_src

** Define Mission Phases

*** Ignite the engines.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpone({
    if maxthrust>0 return mpinc().
    if not stage:ready return 1/10.
    lock throttle to 1.
    lock steering to facing.
    bays off.
  stage. }).
#+end_src

*** damp attitude rate until safe to maneuver

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if alt:radar>=50 return mpinc().
    lock throttle to 1.
    lock steering to facing.
    bays off.
  return 1/10. }).
#+end_src

*** control pitch and heading until apoapsis is high enough

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd(ascent(90,80000)).
#+end_src

*** coast until above atmosphere.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if altitude>body:atm:height return mpinc().
  lock steering to prograde. lock throttle to 0. return 1. }).
#+end_src

*** circularize at apoapsis.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd(simplecirc).
#+end_src

*** drop periapsis to half atmosphere height.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if periapsis<40000 return mpinc().
    lock steering to retrograde.
    lock throttle to max(0,min(1,(periapsis+100-40000)/1000)) *
    max(1/100,min(1,(10-vang(retrograde:vector,facing:vector))/5)).}).
#+end_src

*** configure vessel for re-entry.

Stage ONCE to jettison the orbital maneuvering engines.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({
    lock throttle to 0.
    lock steering to vcrs(body:position,ship:velocity:orbit).
    if altitude>body:atm:height return 1/10.
    if not stage:ready return 1/10.
    if vdot(north:vector,facing:vector) > 5 return 1/10.
  stage. return mpinc(). }).
#+end_src

*** control attitude during upper descent

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if altitude <= 60000 { return mpinc(). }
    lock steering to retrograde. bays off.
  return 1/10. }).
#+end_src

*** control attitude during lower descent until chutes are safe.

The bay doors are open to provide additional drag.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if altitude <= 5000 { return mpinc(). }
    lock steering to srfretrograde. bays on.
  return 1/10. }).
#+end_src

*** Deploy Chutes.

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if not stage:ready return 1/10.
    lock steering to heading(90,90,0).
  stage. return mpinc(). }).
#+end_src

*** damp attitude rates while parachute is armed or deployed

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({ if alt:radar <= 50 return mpinc().
    lock steering to facing.
  return 1/10. }).
#+end_src

*** hold nose vertical during and after landing

#+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
  mpadd({
    lock steering to heading(90,90,0).
  return 1. }).
#+end_src

* Run the Mission, then End the Program.

 #+begin_src ks :results none :tangle ../Archive/home/Aben/Boosted/005 Tourist I/go.ks
   mprun(). print "program terminated".}.
#+end_src

