OKTO I/go.ks: Prototype Satellite System

* What is the typical mission plan?

Example: placing a sattelite in a polar orbit.

- launch when we are under the target orbit
- launch to polar orbit (ie into the plane of the target orbit)
- start from the 80x80km parking orbit
- add maneuver to raise apoapsis to apoapsis of the target orbit
- at apoapsis: add maneuver to raise periapsis to periapsis of the target orbit

Mike's orbit was 790+410 m/s.

Mike says budget 4100 m/s to get into polar orbit.


** Contract 1

BEWARE: MUN is at 11,400,000 with SOI 

- antenna
- generates power
- fully assembled when launched

BEWARE: MUN is at 11,400.000 km
with an SOI radius of about 2430 km,
sweeping up things between 8970 and 13830 km.

| Apoapsis    | 14561.934 | km |
| Periapsis   | 11827.733 | km |
| Inclination |      90.0 | °  |
| LAN         |      92.7 | °  |
| AOP         |      34.0 | °  |

- start in 80x80km parking orbit
- [874.037 m/s] anywhere, raise apoapsis to match target orbit apoapsis
- [316.677 m/s] at apoapsis, change periapsis to match target orbit apoapsis

needs 1190 m/s from parking orbit

ant: 3343 m/s

** Contract 2

- antenna
- generates power
- fully assembled when launched

BEWARE: MUN is at 11,400.000 km
with an SOI radius of about 2430 km,
sweeping up things between 8970 and 13830 km.

| Apoapsis    | 13153.949 | km |
| Periapsis   | 12678.438 | km |
| Inclination |      90.0 | °  |
| LAN         |     352.9 | °  |
| AOP         |       n/a | °  |

- start in 80x80km parking orbit
- [867.132 m/s] anywhere, raise apoapsis to match target orbit apoapsis
- [346.706 m/s] at apoapsis, change periapsis to match target orbit apoapsis

 needs 1213 m/s from parking orbit

* Import Required Packages

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  import("ascent").
  import("fancystager").
  import("hud").
  import("fmt").
  import("ltso").
  import("plan").
  import("time").
  import("mp").
  import("simplecirc").
#+end_src

* During package import: set parameters

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  //set sat_apo to nvget(1,"sat_apo", 14561934).
  //set sat_peri to nvget(1,"sat_peri", 11827733).
  //set sat_inc to nvget(1,"sat_inc", 90.0).
  //set sat_lan to nvget(1,"sat_lan", 92.7).
  //set sat_aop to nvget(1,"sat_aop", 34.0).

  set sat_apo to 14561934.
  set sat_peri to 11827733.
  set sat_inc to 90.0.
  set sat_lan to 92.7.
  set sat_aop to 34.0.
#+end_src
  
#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set sat_orb to soget(sat_apo, sat_peri, sat_inc, sat_lan, sat_aop).
#+end_src

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  plan(sat_apo, sat_peri).
#+end_src


* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set go to {
#+end_src

** Recalibrate MET to start when the GO script starts.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  t0put(0).
#+end_src

** debug helper for "next stage"

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set msgnext to { parameter s. print s. return mpinc(). }.
#+end_src

** Start an autostager in the background

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  fancystager().
#+end_src

** Define Mission Phases

*** set up to launch when we are "under" the assigned orbit.

During boot, we fetch the contract satellite orbital
elements and construct an Orbit object.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks

  local data_csv is home:combine("data.csv").
  deletepath(data_csv).
  local ll is
    TEE()+","+
    fmt("angle_1",8,3)+","+
    fmt("whichway",8,3)+","+
    fmt("h_dot_p",8,3)+","+
    fmt("h_dot_v",8,3).
  print ll.
  log ll to data_csv.

  mpadd({
    if next_time>time:seconds return time:seconds-next_time.
    set next_time to time:seconds + time_per_print.

    // when we are sitting on the ground,
    // our coordinate system rotates with Kerbin.
    // So, BODY:POSITION remains constant,
    // but SAT_H rotates.

    // As we approach our time to launch NORTH,
    // angle_1 will be decreasing toward 90
    // and whichway will be approaching -1.
    //
    // As we approach our time to launch SOUTH,
    // angle_1 will be increasing toward 90
    // and whichway will be approaching +1.

    // data logged near NORTHWARD launch window:
    // 92.170,  -0.999,  -0.038,   0.999       
    // 91.168,  -1.000,  -0.020,   1.000       
    // 90.166,  -1.000,  -0.003,   1.000      
    // 89.163,  -1.000,   0.015,   1.000
    // 88.161,  -0.999,   0.032,   0.999     

    // data logged near SOUTHWARD launch window:
    // 88.412,   1.000,   0.028,  -1.000
    // 89.448,   1.000,   0.010,  -1.000
    // 90.483,   1.000,  -0.008,  -1.000
    // 91.519,   1.000,  -0.027,  -1.000
    // 92.522,   0.999,  -0.044,  -0.999

    // Note that VDOT(sat_norm,-body:position)
    // is the DISTANCE from the target orbital plane
    // to our position, with the sign depending
    // on which side of the plane we are on,
    // and the rate of change is some positive
    // scale factor times VDOT(sat_norm,ship:velocity).

    // We want to launch a bit before one of the
    // two zero-crossing points, NORTH or SOUTH.
    //
    // If the target were not purely polar,
    // we would want to pick the direction
    // that is closer to east.

    local P is body:rotationperiod.
    local time_per_print is P/360.
    local next_time is time:seconds.

    print "Rotation period is "+ydhms(P).
    print "Time per Degree is "+ydhms(P/360).

    local sat_h is vcrs(sat_orb:position-body:position,sat_orb:velocity:orbit).
    local sat_norm is sat_h:normalized.

    local body_to_ship is -body:position:normalized.
    local body_ship_v is ship:velocity:orbit:normalized.

    local angle_1 is vang(body_to_ship, sat_norm).
    local whichway is vdot(north:vector,vcrs(body_to_ship,sat_norm)).

    local h_dot_p is vdot(sat_norm, body_to_ship).
    local h_dot_v is vdot(sat_norm, body_ship_v).

    local ll is
      fmt(angle_1,8,3)+","+
      fmt(whichway,8,3)+","+
      fmt(h_dot_p,8,3)+","+
      fmt(h_dot_v,8,3).

    print ll.
    log ll to data_csv.

    return 5.
  }).
#+end_src

* Run the Mission, then End the Program.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mprun(). print "program terminated".}.
#+end_src
