OKTO I/go.ks: Prototype Satellite System

* Import Required Packages

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  import("nv").
  import("math").
  import("fmt").
  import("mn").
  import("sw").
  import("ascent").
  import("simplecirc").
  import("hud").
#+end_src

** What is the typical mission plan?

Example: placing a sattelite in a polar orbit.

- launch when we are under the target orbit
- launch to polar orbit (ie into the plane of the target orbit)
- start from the 80x80km parking orbit
- add maneuver to raise apoapsis to apoapsis of the target orbit
- at apoapsis: add maneuver to raise periapsis to periapsis of the target orbit

Mike's orbit was 790+410 m/s.

My contract 1: 874+317=1191
My contract 2: 867+347=1214

Mike says budget 4100 m/s to get into polar orbit.

limiting thrust to 20 m/s²:
- My upper stage has 2212 m/s available when it hits space.
- My upper stage has {} m/s available after circularization from -55x80km


* Configuration Parameters and Support Functions

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set go to {
#+end_src

** Configuration Parameters and Support Functions 

*** Set up per-reboot log files


#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set okto_log to home:combine("okto.log").
  if exists(okto_log) open(okto_log):clear().
  log fmt("sa",8,3)+", "+fmt("sf",8,3) to okto_log.
#+end_src

*** Initialize Launch Parameters

These default to simple eastbound parking but
will be explicitly upated in a mission step
just before the actual launch.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set launch_t0 to nvget(1, "launch_t0", t0).
  set launch_az to nvget(1, "launch_az", 90).
  set launch_ap to nvget(1, "launch_ap", 80000).
#+end_src

*** Pick a Mission

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks

  // When we first roll out the vessel,
  // we need to get the contract parameters
  // from a package.

  if not nvhas(1,"ccsma") {
    print "reading current contract".
    import("current_contract").
    deletepath("1:/current_contract").
  } else print "using saved contract data.".

  set ccinc to nvget(1,"ccinc", 0).
  set ccecc to nvget(1,"ccecc", 0).
  set ccsma to nvget(1,"ccsma", 80000).
  set cclan to nvget(1,"cclan", 0).
  set ccaop to nvget(1,"ccaop", 0).
  set ccmep to nvget(1,"ccmep", 0).
  set cctep to nvget(1,"cctep", 0).
  set ccbod to nvget(1,"ccbod", "kerbin").

  set ccorb to CREATEORBIT(ccinc, ccecc, ccsma, cclan, ccaop, ccmep, cctep, ccbod).

#+end_src

*** Estimate ΔV for OMS for this mission.

Uncomment when designing the vessel to obtain
the Delta-V requirements to go from a parking
orbit to the assigned orbit.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  //import("plan"). deletepath("1:/plan.ks").
  //plan_sat(80000,ccorb:periapsis,ccorb:apoapsis,ccorb:body).
#+end_src

** debug helper for "next stage"

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set msgnext to { parameter s. print s. return mpinc(). }.
#+end_src

** pdas -- Point Down At Sun

#+begin_src ks :results none :tangle ../Archive/home/006 Munar Ib/go.ks
  local pdas is {
    local h is vcrs(body:position,ship:velocity:orbit).
    lock throttle to 0.
    lock steering to lookdirup(h,-sun:position).
    local a is vang(facing:upvector,sun:position).
    if a>175 mpinc(). return 1. }.
#+end_src

** Set up staging conditions.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  if stage:number>2
    when stage:number<3 and maxthrust=0 and stage:ready then {
      stage. return stage:number>0. }

  if stage:number>1
    when altitude>70000 and stage:ready then {
      if stage:number>1 stage. return stage:number>1. }
#+end_src

** Define Mission Phases

*** Wait until the next launch window

During boot, we fetch the contract satellite orbital
elements and construct an Orbit object.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpadd({
#+end_src

The coordinate frame is weird when we are landed.
almost like the orientation is always relative to
a point fixed on the surface of the body, but
velocities ignore that it is rotating.

- th: angular momentum direction for target orbit [CHANGES]
- sp: direction from body center to ship center [CONSTANT]
- sv: ship velocity relative to body center to ship center [CONSTANT, NONZERO]

- hp: cosine of angle between th and sp
- hv: cosine of angle between th and sv
- angle: goes from 360 down to 000

I want to launch when we are 2° before the end of the quadrant.
- Before angle is 000, launch NORTHish.
- Before angle is 180, launch SOUTHish.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  local th is vcrs(ccorb:position-body:position,ccorb:velocity:orbit):normalized.
  local sp is -body:position:normalized.
  local sv is ship:velocity:orbit:normalized.
#+end_src

Treat the vectors sp and sv as the basis vectors
for a 2D coordinate system, compute the projection
of the th vector onto that plane, then pick out
an angle within that plane.
 
#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  local hp is vdot(th, sp).
  local hv is vdot(th, sv).
#+end_src

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  local angle is arctan2(hv, hp)+180.
#+end_src

TODO estimate how long until a good launch window
use SAFEWARP to get us close
When we are close to the window:
- double check that WARP is 0 and SETTLED
- lock down the launch time T0
- pass control to the COUNTDOWN step

pick behavior based on quadrant.
angle is increasing over time.

- Quad 3: approaching NORTH departure
- Quad 2: after NORTH before SOUTH
- Quad 1: approaching SOUTH departure
- Quad 0: after SOUTH before NORTH

If we are in Quadrant 0 or 2,
use safewarp to manage warping
into the next quadrant.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  local quad is floor(angle/90).
  if quad=0 or quad=2 {swadj(body:rotationperiod/8). return 1/10.}
#+end_src

Otherwise, use safewarp to manage warping
to a comfortable margin before the
end of the current quadrant.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  local aeoq is angle-90*quad.
  local qeta is aeoq * body:rotationperiod/360.

  // we can bias qeta to rotate our resulting orbital plane
  // around kerbin's axis. It looks like I need to lead the
  // target plane by about 2°.
  set qeta to qeta - 2*body:rotationperiod/360.

  swadj(qeta-30).
  if warp>0 or not kuniverse:timewarp:issettled return 1/10.
#+end_src

If we get here, we are close to the end of a launch
quadrant. Uncomment this to remind me of what values we
computed above.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  log TEE()+": "+
    "hp: "+fmt(hp,8,5)+", "+
    "hv: "+fmt(hv,8,5)+", "+
    "angle: "+fmt(angle,8,3)+", "+
    "qeta: "+fmt(qeta,8,3) to okto_log.
#+end_src

Leading up to the NORTHish launch window:

Leading up to the SOUTHish launch window:

Monitor numbers closely until 20 seconds before the estimated launch
window. Continue the process if the rounded qeta is 20 seconds or les.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  if qeta>20 return 1-mod(met()+100,1)-1/10.
#+end_src

We are close enough that we can commit to the
launch parameters (t0, az, ap) and move along to the
next step in the plan.

For polar orbits, push launch azimuth west by four degrees.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  t0put(qeta-10).
  set launch_t0 to nvput(1, "launch_t0", t0).
  set launch_az to nvput(1, "launch_az", choose 356 if hv > 0 else 184).
  set launch_ap to nvput(1, "launch_ap", 80000).
  return mpinc(). }).
#+end_src

*** Provide a brief countdown.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpadd({
    local t is -met().
    if t<=5.5 print TEE().
    if t<=0.5 return mpinc().
    return mod(t,1).
  }).

#+end_src

*** Ignite the engines.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpone({
    if maxthrust>0 return mpinc().
    if not stage:ready return 1/10.
    lock throttle to 1.
    lock steering to facing.
    hud("ignition"). stage. t0put(0).
    set launch_t0 to nvput(1, "launch_t0", t0).
  }).
#+end_src

*** damp attitude rate until safe to maneuver

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpadd({ if alt:radar>=50 return mpinc().
    lock throttle to 1. lock steering to facing. return 1/10. }).
  mpone({hud("pitchover").}).
#+end_src

*** control pitch and heading until apoapsis is high enough

Ascent controller for a desired launch azimuth and altitude.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpadd({
#+end_src

If we are coming down, end the step (this is bad).
If we are above the atmosphere and our apoapsis
is high enough, end the step (this is good).

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  if verticalspeed<0 return mpinc().
  if altitude>=70000 and apoapsis>=launch_ap return mpinc().
#+end_src

TODO use an error controller to manage the heading part
of the steering so that we land on the desired plane.
- initially steer to the inclination of the orbit
- at some threshold altitude or velocity, activate.
- null option:
  - steer along the indicated azimuth until done
- option 0:
  - steer along the indicated azimuth
  - look for our orbit inclination to be right
  - switch to steering along our orbit
- option 1:
  - compare current orbit inclination with desired inclination,
    steer to fix the inclination only.
- option 2:
  - determine distance from plane
  - determine velocity toward plane
  - set plane-normal component of thrust to control toward-plane velocity

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  lock af to limit(0,1,altitude/launch_ap).
  lock cp to limit(0,90,90-120*sqrt(af)).
  lock steering to heading(launch_az, cp, 0).
#+end_src

Rather than go full-throttle all the way, limit our
acceleration during ascent.

NOTE: limiting to 15 m/s does not get uws high enough fast enough.
NOTE: limiting to 20 m/s works better but I think it could be higher.
- control passed to upper stage at ~45 km.
- ants were quite good at fine tuning initial 80km apoapsis.
- 2213 m/s remaining before simplecirc
- simplecirc worked just fine, good margin
- 2084 m/s remaining after simplecirc
- inclination: 89.919°		wanted 90.000°
- lan: 92° 24' 41" = 94.4°        wanted 92.700°

Hold on, I thought I rotated angle back by 2° to fix lan.

- *IDEA FROM MIKE* reduce thrust when apoapsis is more
  than 55 seconds ahead of us. Not a lot more efficient
  but a lot less hectic and looks cooler.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  lock tf to min(1,sqrt(max(0,(launch_ap+20-apoapsis)/1000))).
  lock mt to max(eps, ship:availablethrust).
  lock throttle to tf*min(1,20*mass/mt).
#+end_src

re-evaluate the ascent every second.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  return 1. }).
#+end_src

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpone({hud("vs="+verticalspeed+", apo="+apoapsis+", la="+launch_ap).}).
  mpone({lock throttle to 0. hud("MECO").}).
#+end_src

*** coast until above atmosphere.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpadd({ if altitude>body:atm:height return mpinc().
  lock steering to prograde. lock throttle to 0. return 1. }).
  mpone({hud("SPACE!").}).
#+end_src

*** circularize at apoapsis.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mpone({hud("simplecirc...").}).
  mpadd(simplecirc).
  mpone({hud("ORBIT!").}).
    // I think we stage here to discard farings.
#+end_src

*** 

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
#+end_src

*** 

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
#+end_src

*** 

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
#+end_src

*** 

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
#+end_src

*** 

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
#+end_src

* Run the Mission, then End the Program.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mprun(). print "program terminated".}.
#+end_src
