OKTO I/go.ks: Prototype Satellite System

* Import Required Packages

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  import("nv").
  import("math").
  import("fmt").
  import("fancystager").
  import("mn").
  import("sw").
#+end_src

** What is the typical mission plan?

Example: placing a sattelite in a polar orbit.

- launch when we are under the target orbit
- launch to polar orbit (ie into the plane of the target orbit)
- start from the 80x80km parking orbit
- add maneuver to raise apoapsis to apoapsis of the target orbit
- at apoapsis: add maneuver to raise periapsis to periapsis of the target orbit

Mike's orbit was 790+410 m/s.

Mike says budget 4100 m/s to get into polar orbit.

* Configuration Parameters and Support Functions

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set go to {
#+end_src

** Configuration Parameters and Support Functions 

*** Pick a Mission
#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks

  // When we first roll out the vessel,
  // we need to get the contract parameters
  // from a package.

  if not nvhas(1,"ccsma") {
    print "reading current contract".
    import("current_contract").
    deletepath("1:/current_contract").
  } else print "using saved contract data.".

  set ccinc to nvget(1,"ccinc", 0).
  set ccecc to nvget(1,"ccecc", 0).
  set ccsma to nvget(1,"ccsma", 80000).
  set cclan to nvget(1,"cclan", 0).
  set ccaop to nvget(1,"ccaop", 0).
  set ccmep to nvget(1,"ccmep", 0).
  set cctep to nvget(1,"cctep", 0).
  set ccbod to nvget(1,"ccbod", "kerbin").

  set ccorb to CREATEORBIT(ccinc, ccecc, ccsma, cclan, ccaop, ccmep, cctep, ccbod).

#+end_src

*** Estimate ΔV for OMS for this mission.

Uncomment when designing the vessel to obtain
the Delta-V requirements to go from a parking
orbit to the assigned orbit.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  import("plan"). deletepath("1:/plan.ks").
  plan_sat(80000,ccorb:periapsis,ccorb:apoapsis,ccorb:body).
#+end_src

** Recalibrate MET to start when the GO script starts.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  t0put(0).
#+end_src

** debug helper for "next stage"

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  set msgnext to { parameter s. print s. return mpinc(). }.
#+end_src

** Start an autostager in the background

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  fancystager().
#+end_src

** Define Mission Phases

*** set up to launch when we are "under" the assigned orbit.

During boot, we fetch the contract satellite orbital
elements and construct an Orbit object.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks

  // kerbin rotates one degree in 59.860 seconds.

  local data_csv is home:combine("data.csv").
  deletepath(data_csv).
  local ll is
    TEE()+","+
    fmt("h dot p",8,3)+","+
    fmt("h dot v",8,3)+","+
    fmt("angle",8,3)+","+
    fmt("quad",5,0)+","+
    fmt("aeoq",8,3)+","+
    fmt("qeta",8,3).

  print "ll                      "+ll.
  log ll to data_csv.

  local next_log_time is time:seconds.

  mpadd({

    // The coordinate frame is weird when we are landed.
    // almost like the orientation is always relative to
    // a point fixed on the surface of the body, but
    // velocities ignore that it is rotating.

    // th: angular momentum direction for target orbit [CHANGES]
    // sp: direction from body center to ship center [CONSTANT]
    // sv: ship velocity relative to body center to ship center [CONSTANT, NONZERO]

    local th is vcrs(ccorb:position-body:position,ccorb:velocity:orbit):normalized.
    local sp is -body:position:normalized.
    local sv is ship:velocity:orbit:normalized.

    // When hp is zero and hv is -1 (angle is 090) launch to the SOUTH.
    // When hp is zero and hv is +1 (angle is 270) launch to the NORTH.
    // TODO If the target is not exactly polar, what happens?
    // TODO If the target is nearly equatorial, what happens?

    local h_dot_p is vdot(th, sp).
    local h_dot_v is vdot(th, sv).

    // make the angle go from 360 to 000
    // the angle DECREASES over time.
    local angle is arctan2(h_dot_v, h_dot_p)+180.

    // TODO estimate how long until a good launch window
    // use SAFEWARP to get us close
    // When we are close to the window:
    // - double check that WARP is 0 and SETTLED
    // - lock down the launch time T0
    // - pass control to the COUNTDOWN step

    // pick behavior based on quadrant.
    // angle is increasing over time.

    local quad is floor(angle/90).
    if quad=0 or quad=2 {swadj(body:rotationperiod/8). return 1/10.}
    local aeoq is angle-90*quad.
    local dadt is 360/body:rotationperiod.
    local qeta is aeoq / dadt.

    swadj(qeta-30). // swadj needs to be called FREQUENTLY when warping.
    if warp>0 or not kuniverse:timewarp:issettled return 1/10.

    // Quad 3: approaching NORTH departure
    // Quad 2: after NORTH before SOUTH
    // Quad 1: approaching SOUTH departure
    // Quad 0: after SOUTH before NORTH

    set next_log_time to next_log_time + body:rotationperiod/360.

    local ll is TEE()+","+
      fmt(h_dot_p,8,3)+","+
      fmt(h_dot_v,8,3)+","+
      fmt(angle,8,3).

    set ll to ll+","+fmt(quad,5,0)+","+fmt(aeoq,8,3)+","+fmt(qeta,8,3).

    print "ll                      "+ll.
    log ll to data_csv.
    return mod(qeta-1/10,5).
  }).
#+end_src

* Run the Mission, then End the Program.

#+begin_src ks :results none :tangle ../Archive/home/007 OKTO I/go.ks
  mprun(). print "program terminated".}.
#+end_src
