fancystager.ks - fancy auto-stager

* Import Required Packages

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  import("mp").
#+end_src

* Set up the fancystager delegate

The "fancy" stager looks at a lists of
engines and fuel tank parts that would
be jettisoned at the current stage.

A stage command is issued if all engines
are flamed out and no useful amount of
fuel remains in any of the tanks.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  set fancystager to {
#+end_src

** Initialize engine and tank lists

*** lol: helper function to set up a list of N lists.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  local lol is { parameter n. local res is list().
  until res:length >= n res:add(list()). return res. }.
#+end_src

*** loe: list of engines for stages 0 through stage:number

Specifically, loe[N] is the list of engines that
are DECOUPLED when we move to stage N.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  local loe is lol(stage:number+1).
  for en in ship:engines
    loe[en:decoupledin]:add(en).
#+end_src

*** lot: list of fuel resources for stages 0 through stage:number

Specifically, lot[N] is the list of (part,resource)
pairs for all parts containing Liquid Fuel that are
DECOUPLED when we move to stage N.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  local lot is lol(stage:number+1).
  for p in ship:parts
    for res in p:resources
    if res:name="LiquidFuel"
    lot[p:decoupledin]:add(list(p,res)).
#+end_src

** Start the scheduled job

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  local t is time:seconds.
  local mt is 0.
  when t <= time:seconds then {
#+end_src

*** Stop the periodic job on ABORT or STAGE ZERO.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  if abort or stage:number<1 return false.
#+end_src

*** Pick the next scheduled time.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  set t to time:seconds + 1. 
#+end_src

*** Early return: too low, or staging not ready.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  if not stage:ready or alt:radar<100 return true.
#+end_src

*** All engines must be flamed out

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  for en in loe[stage:number-1]
    if not en:flameout
    return true.
#+end_src

*** All resources must be effectively exhausted

Our engines burn both Liquid Fuel and Ozidizer, and
the fuel tanks have them in the right ratio, but when
the engine flames out there may be a very small amount
of Liquid Fuel remaining in the tank.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  for pr in lot[stage:number-1]
    if pr[1]:amount>0.01
  return true.
#+end_src

*** Trigger staging, and keep the job running.

#+begin_src ks :results none :tangle ../Archive/fancystager.ks
  stage.
  return true. }}.
#+end_src
