#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../Archive/fancystager.ks

fancystager.ks - fancy auto-stager

* Supports ONION staging.

* Launch Clamps just work.

* FARING NOTES:

Using STAGE to deploy farings also performs
a stack separation at the faring base. Vessels
must place the faring in the staging list at
the appropriate point, based on separation, not
on where it is best to deploy the shell.

* Import Required Packages

#+begin_src ks
  import("mp").
  import("sw").
  import("fmt").
  import("time").
  import("logger").
#+end_src

* Package Data

** log_stager: logging function

#+begin_src ks
  local log_stager is mklogger("fancystager").
#+end_src

** lol: helper function to set up a list of N lists.

#+begin_src ks
  local lol is { parameter n. local res is list().
  until res:length >= n res:add(list()). return res. }.
#+end_src

** loe: list of engines for stages 0 through stage:number

Specifically, loe[N] is the list of engines that
are DECOUPLED when we move to stage N.

#+begin_src ks
  local loe is lol(stage:number+1).
  for en in ship:engines
    if en:decoupledin>=0
      loe[en:decoupledin]:add(en).
#+end_src

** lolf: list of liquid fuel resources for stages 0 through stage:number

Specifically, lolf[N] is the list of (part,resource)
pairs for all parts containing Liquid Fuel that are
DECOUPLED when we move to stage N.

#+begin_src ks
  local lolf is lol(stage:number+1).
  for p in ship:parts
    if p:decoupledin>=0
      for res in p:resources
        if res:name="LiquidFuel"
          lolf[p:decoupledin]:add(list(p,res)).
#+end_src

** loox: list of oxidizer resources for stages 0 through stage:number

Specifically, loox[N] is the list of (part,resource)
pairs for all parts containing Oxidizer that are
DECOUPLED when we move to stage N.

#+begin_src ks
  local loox is lol(stage:number+1).
  for p in ship:parts
    if p:decoupledin>=0
      for res in p:resources
        if res:name="Oxidizer"
          loox[p:decoupledin]:add(list(p,res)).
#+end_src

** lof: list of farings for stages 0 through stage:number

Specifically, lolf[N] is the list of Parts associated
with stage N that have LaunchClamp modules.

#+begin_src ks
  local lof is lol(stage:number+1).
  for p in ship:parts
    if p:hasmodule("FaringSometing")
      lof[p:stage]:add(p).
#+end_src

* Set up the fancystager delegate

The "fancy" stager looks at a lists of
engines and fuel tank parts that would
be jettisoned at the current stage.

A stage command is issued if all engines
are flamed out and no useful amount of
fuel remains in any of the tanks.

#+begin_src ks
  set fancystager to {
#+end_src

** Start the scheduled job

#+begin_src ks
  local t is time:seconds.
  when t <= time:seconds then {
#+end_src

*** Stop the periodic job on ABORT or STAGE ZERO.

#+begin_src ks
  if abort or stage:number<1 return false.
#+end_src

*** Pick the next scheduled time.

#+begin_src ks
  set t to time:seconds+1/10.
#+end_src

*** Early return: too early, or before launch.

#+begin_src ks
  if not stage:ready or met()<=0 return true.
#+end_src

*** All engines must be flamed out

If any engine that would be discarded by staging
is still running (not flamed out), do not stage.

#+begin_src ks
  for en in loe[stage:number-1]
    if not en:flameout return true.
#+end_src

*** All resources must be effectively exhausted

This is aimed at Onion Staging configurations, where
tanks jettisoned on one stage are feeding engines
jettisoned on a higher stage.

These tanks do not always drain to exactly zero,

Tanks containing Liquid Fuel and Oxidizer need to
be "effectively" drained -- that is, low enough that
the engines they feed would be flamed out, if these
tanks were their only fuel source.

Nonzero thresholds observed:

- Kemini I Stage 2, "Swivel" engine drawing from 3xFL-T400,
  total of 0.0035 LF and 0.0043 OX remains in all tanks.

It might be more correct to chase down all engines that
are currently active and base the threshold on their fuel
flow rates, but a fixed threshold Should Work Fine.

#+begin_src ks
  local tlf is 0.
  for pr in lolf[stage:number-1]
    set tlf to tlf + pr[1]:amount.
#+end_src

#+begin_src ks
  local tox is 0.
  for pr in loox[stage:number-1]
    set tox to tox + pr[1]:amount.
#+end_src

#+begin_src ks
  for pr in lolf[stage:number-1]
    log_stager("observed "+
      fmt(pr[1]:amount,8,4)+" "+
      pr[1]:name+" in "+pr[0]:title).
  for pr in loox[stage:number-1]
    log_stager("observed "+
      fmt(pr[1]:amount,8,4)+" "+
      pr[1]:name+" in "+pr[0]:title).
  log_stager("total "+
    fmt(tlf,8,4)+" lf, "+
    fmt(tox,8,4)+" ox "+
    "in stage "+stage:number).
#+end_src

#+begin_src ks
  if tlf>0.01 and tox>0.01 return true.
#+end_src

*** DO NOT STAGE WHILE WARPING.

If we get here, we really do want to stage.

If we are in TIMEWARP when it comes time to stage,
cancel timewarp, wait for it to settle, wait for the
steering to settle, then wait for one more second for
good measure. Staging just after coming out of timewarp
when we may be rotating rapidly would risk damaging
things that need to not be damaged.

#+begin_src ks
  if warp>0 set warp to 0.
  if not kuniverse:timewarp:issettled {
    wait until kuniverse:timewarp:issettled.
    wait until vang(steering:vector,facing:vector)<5.
    wait 1.}
#+end_src

*** Trigger staging, and keep the job running.

#+begin_src ks
  log_stager("staging from stage "+stage:number).
  stage. return true. }}.
#+end_src
