#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../Archive/go.ks

go.ks -- GO script for missions that do not yet have a GO script.

This script will be run when IMPORT is unable to find a GO script in
the HOME directory, or any parent of it, until it finds this script
in the root of the archive.

This script creates the GO script for the ship by giving it
a copy of the "GONEW" package.

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  function go {
#+end_src

Copy the "gonew" package from wherever it is found
into the home directory as the new "go" package.

Note that "gonew" packages can be provided for entire groups of ships:
"Orbiter/gonew.ks" will be used for "Orbiter/mun" and "Orbiter/minmus"
if they are created without go scripts, and if there is no GO script
in "0:home/Orbiter/go.ks".

#+begin_src ks
  local p is home:combine("go.ks").
  copypath(find("gonew"), p).
#+end_src

Inform the flight engineer that it has done so.

#+begin_src ks
  print "New GO script created:".
  print "  "+p.
#+end_src

Automatically reboot, which will now pull in
the new GO script template.

#+begin_src ks
  print "rebooting into new GO script in 3 seconds.".
  wait 3.
  reboot. }
#+end_src
