math - simple math stuff

* Constants (pi, g0, e, inf, eps)

NOTE: the INF value used here must be less than the
10^38 value returned by KOS functions that are returning
a value indicating HUGE, such as ETA:APOAPSIS for
hyperbolic trajectories.

However note, testing for hyperbolic is better done
by looking for negative APOAPSIS values.

#+begin_src ks :results none :tangle ../Archive/math.ks
  set pi to constant:pi.
  set g0 to constant:g0.
  set e to constant:e.
  set inf to 10^30.
  set eps to 1/inf.
#+end_src

* limit(L,H,U): clamp a value within a range.

This is used when a value U needs to be restricted
to be within the L..H range. Returns L if U is less
than L. Returns H if L is higher than H.

Caller must assure that L <= H.

#+begin_src ks :results none :tangle ../Archive/math.ks
  set limit to { parameter l,h,u. return max(l,min(h,u)). }.
#+end_src

* ua(a): fold angle a into the 000..360 range.

#+begin_src ks :results none :tangle ../Archive/math.ks
  set ua to { parameter a. return choose 360-mod(-a,360) if a<0 else mod(a,360). }.
#+end_src

* sa(a): fold angle a into the -180..+180 range.

#+begin_src ks :results none :tangle ../Archive/math.ks
  set sa to { parameter a. return ua(a+180)-180. }.
#+end_src

* vv(r1,r2,r3,mu): use vis-viva to calculate velocity

Vis-Viva Equation: v² = μ ( 2/r - 1/a )

Returns the velocity of a test mass at radius r1 moving
in an orbit with periapsis radius r2 and apoapsis radius
r3, in a gravitational field defined by MU = G*(M1+M2).

#+begin_src ks :results none :tangle ../Archive/math.ks
  set vv to { parameter r1,r2,r3,mu.
  return sqrt(max(0,2*mu*(1/r1-1/(r2+r3)))). }.
#+end_src

* burndv(r1,r2,r3,mu): compute ΔV from two vis-viva computations.

At radius R1, transitioning from an R1xR2 orbit to an R1xR3 orbit
where the R values are radii, not altitudes, and are in meters.

#+begin_src ks :results none :tangle ../Archive/math.ks
  set burndv to { parameter r1,r2,r3,mu.
    return vv(r1,r1,r3,mu)-vv(r1,r1,r2,mu). }.
#+end_src

* burndvh(h1,h2,h3,b): burndv but using altitudes

Variant of burndv that takes input as METERS ASL, and the body.

#+begin_src ks :results none :tangle ../Archive/math.ks
  set burndvh to { parameter h1,h2,h3,b.
    local r0 is b:radius.
    return burndv(r0+h1,r0+h2,r0+h3,b:mu). }.
#+end_src

* lefthand(vec): adjust vector for use in CREATEORBIT calls

see: https://github.com/KSP-KOS/KOS/issues/2862
see: https://github.com/KSP-KOS/KOS/issues/3009

Dunbaratu, comment on issue 2862, on Jan 26, 2021:
> When using CREATEORBIT, the position and velocity
> vectors must each have their Y and Z axes swapped.
> KSP, for some unknown reason, when talking about
> planetary values transposes y and z axes and kOS has
> to constantly be aware of those weird cases and
> correct for them. It's not enough to just rotate or
> translate to go between reference frames, it literally
> has to swap axes to do it. This is apparently such a
> case and it wasn't made clear because KSP mod devs
> already know this weird ugly misfeature in KSP but
> most kOS users are protected from it.

Dunbaratu, comment on issue 3009, on Aug 26, 2021:
> I had a look and yup, you're right. It calls the KSP
> method Orbit.UpdateFromStateVectors() which apparently
> uses the same messed up Y/Z axis-swap that KSP
> sometimes uses for other body-relative calls like in
> geopositions, and the kOS code doesn't compensate for
> that like it does when you pass a position into, say,
> body:geopositionof(vector).

#+begin_src ks :results none :tangle ../Archive/math.ks
  set lefthand to { parameter u. return v(u:x,u:z,u:y). }.
#+end_src
