mn - maneuver node support

* Import All Dependencies

#+begin_src ks :results none :tangle ../Archive/mn.ks
  import("math").
  import("mp").
  import("sw").
  import("bt").
  import("predict").
  import("time").
#+end_src

* mnclr -- Cancel Pending Maneuvers

This is the most compact way I have found to cancel all
scheduled maneuver nodes. I was a bit nervous about
whether iterating through allnodes would have problems
with a node being removed during the iteration, but it
does seem to work just fine.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mnclr to { for n in allnodes remove n. }.
#+end_src

* mnexec -- STEP: execute the next maneuver node

#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mnexec to {
#+end_src

** if no maneuver is scheduled, this step is complete.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if not hasnode return mpinc().
#+end_src

** assure we are not in timewarp.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if warp>0 set warp to 0.
  if not kuniverse:timewarp:issettled return 1/10.
#+end_src

** if we are out of fuel, we are done.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if ship:liquidfuel <= 0 return mpinc().
#+end_src

** if the remaining ΔV is trival, we are done.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  local mnv is nextnode.
  if mnv:deltav:mag<1/10 return mpinc().
#+end_src

** Steer in the direction of the burn.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  lock steering to mnv:deltav.
#+end_src

** Throttle Management

Throttle is the product of two 0..1 values.
- A value decreasing from 1 to 0 as ΔV approaches 0
- A value decreasing from 1 to 0 if we are not pointing the right way

#+begin_src ks :results none :tangle ../Archive/mn.ks
  lock mnl_mt to max(eps, maxthrust).
  lock mnl_dv to mnv:deltav:mag.
  lock mnl_dt to mnl_dv * ship:mass / mnl_mt.
  lock mnl_dtdf to limit(0,1,mnl_dt/0.5).
  lock mnl_ae to vang(mnv:deltav,facing:vector).
  lock mnl_aedf to limit(1/100,1,1-(mnl_ae-1)/4).
  lock throttle to sqrt(mnl_dtdf * mnl_aedf).
#+end_src

** When to revisit the computation

Come back and recompute in no longer than a second.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  return min(1,mnl_dt). }.
#+end_src

* mnfini -- STEP: clean up after mnexec

The mnexec step leaves the (nearly) exhausted maneuver
node scheduled and leaves THROTTLE and STEERING locked
as they were at the end of the burn.

This function cuts the throttle, sets steering to keep
our attitude where it is, and clears the maneuver plan.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  // All uses of mnexec must be immediately followed by mnfini.
  // Missions should probably also fix the facing.
  set mnfini to {
    lock throttle to 0.
    lock steering to facing.
    mnclr().
    return mpinc().
  }.
#+end_src

* mnwait -- STEP: wait until time to start the burn for the maneuver node

It is the responsibility of the mission to assure
that we are in a good state to wait for the next
maneuver node.

- the ship is not timewarping
- the ship is not currently producing thrust

#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mnwait to {
#+end_src

If no maneuver is planned, or if the maneuver is
trivially overdue, move on to the next step.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if not hasnode return mpinc().
  local mnv is nextnode.
  if mnv:eta <= 0 return mpinc().
#+end_src

Work out when to start the burn, based on
wanting to provide half of the ΔV before
the scheduled burn instant and half after.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  local hbt is bt(mnv:deltav:mag/2).
  local dt is mnv:eta - hbt.
#+end_src

BE CAREFUL: vessel is probably currently maintaining an
attitude that keeps batteries charged. Do not mess with
steering until 60 seconds before the burn, avoid trying
to steer into a V(0,0,0) deltav, ando handle the case
where the node goes away before someone else takes over
steering.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if dt < 60
    lock steering to
      choose mnv:deltav
      if hasnode and mnv:deltav:mag > 0
      else facing.
#+end_src

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if dt <= 0 return mpinc().
#+end_src

The swadj function computes the warp factor right now
that would allow us to come to a halt at the given time.
But we DO need to call it frequently so it can lower the
warp factor in time!

#+begin_src ks :results none :tangle ../Archive/mn.ks
  swadj(dt-30). return 1/10. }.
#+end_src

* mncirc -- STEP: plan maneuver to circularize at next periapsos or apoapsis

It is the responsibility of the mission to assure
that we are in a good state to plan and execute
a maneuver node.

- the ship is not timewarping
- the ship is not currently producing thrust
- the ship is able to produce thrust
- there are no pending maneuver nodes

These conditions checked during flight will prevent
us from building a node:
- we are outbound on an escape orbit
- the correction burn would be trivial

#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mncirc to {
#+end_src

Cancel any existing maneuver nodes.
This is useful if we reboot after setting up the
node but before the mission step is updated.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  mnclr().
#+end_src

Pick the periapsis or apoapsis ETA, whichever is sooner.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  local dt is min(eta:periapsis, eta:apoapsis).
#+end_src

The node we build below only works if our burn is
precisely progade or retrograde, so we are good for
elliptical orbits, or generally when inbound.

If we are outbound on an escape orbit, eta:apoapsis
will be HUGE and eta:periapsis will be NEGATIVE. In
this case, return without making a maneuver node.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if dt>0 and dt<inf {
#+end_src

Compute delta-v to change our prograde speed to
be exactly the circular orbit speed.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  local t is time:seconds+dt.
  local dv is sqrt(body:mu/posat(t,ship):mag)-velat(t,ship):mag.
#+end_src

quick estimate of burntime is ΔV*mass/thrust, actually a
bit shorter but we want a QUICK estimate at this point.

If the burn is nontrivial based on this rough estimate,
add it to the maneuver schedule.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  if abs(dv)*mass*1000>=maxthrust add node(t,0,0,dv).
#+end_src

#+begin_src ks :results none :tangle ../Archive/mn.ks
  } return mpinc(1/50).}.
#+end_src

* mnth(t,h) -- SUPPORT: build node for time T to set opposing altitude to H.

Establish a node centered at T seconds UT which
sets the periapsis and apoapsis to the altitude
at time T, and the altitude given as H.

Works best if the altitude at time T is near the
current periapsis or apoapsis.

This will include a radial component to cancel
the existing radial velocity at T, along with
the prograde component to adjust the altitude
of the opposing point.

The computation of the prograde component takes
into account the fact that the radial component
will change periapsis and apoapsis, but does
not change the semi-major axis.

In normal usage, the magnitude of the prograde
component will dominate the burn.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mnth to {
    parameter t.
    parameter h.
    local mu is body:mu.
    local r0 is body:radius.
    local r1 is posat(t,ship).
    local v1 is velat(t,ship).
    local vr is vdot(v1,r1:normalized).
    local dp is burndv(r1:mag,r0*2+apoapsis+periapsis-r1:mag,r0+h,mu).
    return node(t,-vr,0,dp). }.
#+end_src

* mnatp(h) -- STEP BUILDER: at periapis, set other altitude to h.

It is the responsibility of the mission to assure
that we are in a good state to plan and execute
a maneuver node.

- the ship is not timewarping
- the ship is not currently producing thrust
- the ship is able to produce thrust
- there are no pending maneuver nodes

These conditions checked during flight will prevent
us from building a node:
- we are outbound on an escape orbit
- the correction burn would be trivial

If the burn to raise the apoapsis would be the
same at our periapsis and our apoapsis, then
schedule the burn to commence immediately.

Procedure:

- Cancel any existing maneuver nodes.
  This is useful if we reboot after setting up the
  node but before the mission step is updated.

- Do nothing more if we are outbound on a hyperbolic
  orbit, detected by eta:periapsis being negative.

- Center the burn at the periapsis.

- Use MNTH above to set up a node, and schedule it
  if the prograde burn is nontrivial.

NOTE: this might schedule a burn that is TOO SOON,
in that we could not possibly achieve half of the
burn before the scheduled time.


#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mnatp to { parameter des_apo. return {
    mnclr().
    if eta:periapsis<0 return mpinc().
    local mnv is mnth(time:seconds+eta:periapsis,des_apo).
    if bt(mnv:prograde)>1/1000 add mnv.
    return mpinc(1/50).}.}.
#+end_src

* mnata(h) -- STEP BUILDER: at apoapsis, set other altitude to h.

It is the responsibility of the mission to assure
that we are in a good state to plan and execute
a maneuver node.

- the ship is not timewarping
- the ship is not currently producing thrust
- the ship is able to produce thrust
- there are no pending maneuver nodes

These conditions checked during flight will prevent
us from building a node:
- we are outbound on an escape orbit
- the correction burn would be trivial

If the burn to raise the periapsis would be the
same at our apoapsis and our periapsis, then
schedule the burn to commence immediately.

Procedure:

- Cancel any existing maneuver nodes.
  This is useful if we reboot after setting up the
  node but before the mission step is updated.

- Do nothing more if we are on a hyperbolic orbit,
  detected by apoapsis being negative.

- Center the burn at the apoapsis. 

- Use MNTH above to set up a node, and schedule it
  if the prograde burn is nontrivial.

#+begin_src ks :results none :tangle ../Archive/mn.ks
  set mnata to { parameter des_peri. return {
    mnclr().
    if apoapsis<0 return mpinc().
    local mnv is mnth(time:seconds+eta:apoapsis,des_peri).
    if bt(mnv:prograde)>1/1000 add mnv.
    return mpinc(1/50).}.}.
#+end_src
