#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../Archive/mn.ks

mn - maneuver node support

* Import All Dependencies

#+begin_src ks
  import("math").
  import("mp").
  import("sw").
  import("bt").
  import("predict").
  import("time").
#+end_src

* mnclr -- Cancel Pending Maneuvers

This is the most compact way I have found to cancel all
scheduled maneuver nodes. I was a bit nervous about
whether iterating through allnodes would have problems
with a node being removed during the iteration, but it
does seem to work just fine.

#+begin_src ks
  set mnclr to { for n in allnodes remove n. }.
#+end_src

* mnexec -- add STEP to execute the next maneuver node

#+begin_src ks
  set mnexec to { mpadd({
#+end_src

** if no maneuver is scheduled, this step is complete.

#+begin_src ks
  if not hasnode return mpinc().
#+end_src

** assure we are not in timewarp.

#+begin_src ks
  if warp>0 set warp to 0.
  if not kuniverse:timewarp:issettled return 1/10.
#+end_src

** if we are out of fuel, we are done.

#+begin_src ks
  if ship:liquidfuel <= 0 { mnclr(). return mpinc(). }
#+end_src

** if the remaining work is trival, we are done.

#+begin_src ks
  local mnv is nextnode.
  local dv is mnv:deltav:mag.
  local dt is bt(dv).
  if dv<1/10 or dt<1/1000 {
    lock throttle to 0.
    lock steering to facing.
    remove mnv.
    return mpinc().
  }
#+end_src

** Steer in the direction of the burn.

It is possible for mnv:deltav to become zero, but it is not expected
that we will ever actually see that happen.

#+begin_src ks
  lock steering to mnv:deltav.
#+end_src

** Throttle Management

Throttle is the product of two 0..1 values.
- A value decreasing from 1 to 0 as ΔV approaches 0
- A value decreasing from 1 to 0 if we are not pointing the right way

#+begin_src ks
  // lock mnl_mt to max(eps, availablethrust).
  // lock mnl_dv to mnv:deltav:mag.
  // lock mnl_dt to mnl_dv * ship:mass / mnl_mt.
  // lock mnl_dtdf to limit(0,1,mnl_dt/0.5).
  // lock mnl_ae to vang(mnv:deltav,facing:vector).
  // lock mnl_aedf to limit(1/100,1,1-(mnl_ae-1)/4).
  // lock throttle to sqrt(mnl_dtdf * mnl_aedf).

  // use the quick-and-dirty method for estimating ΔT from the known ΔT
  // as they converge near the end of the burn.

  lock throttle to sqrt(
    limit(0,1,2*mnv:deltav:mag*ship:mass/max(eps,availablethrust)) *
    limit(1/100,1,1-(vang(mnv:deltav,facing:vector)-1)/4)).
#+end_src

** When to revisit the computation

Come back often enough to promptly detect
that our job is done.

#+begin_src ks
  return 1.}).}.
#+end_src

* mnfini -- add STEP to clean up after mnexec

The mnexec step leaves the (nearly) exhausted maneuver
node scheduled and leaves THROTTLE and STEERING locked
as they were at the end of the burn.

This function cuts the throttle, sets steering to keep
our attitude where it is, and clears the maneuver plan.

#+begin_src ks
  // All uses of mnexec must be immediately followed by mnfini.
  // Missions should probably also fix the facing.
  set mnfini to { mpadd({
    lock throttle to 0.
    lock steering to facing.
    mnclr().
    return mpinc().}).}.
#+end_src

* mnwait -- add STEP to wait until time to start the burn for the maneuver node

It is the responsibility of the mission to assure
that we are in a good state to wait for the next
maneuver node.

- the ship is not timewarping
- the ship is not currently producing thrust

#+begin_src ks
  set mnwait to { mpadd({
#+end_src

If no maneuver is planned, or if the maneuver is
trivially overdue, move on to the next step.

#+begin_src ks
  if not hasnode return mpinc().
  local mnv is nextnode.
  if mnv:eta <= 0 return mpinc().
#+end_src

Work out when to start the burn, based on
wanting to provide half of the ΔV before
the scheduled burn instant and half after.

#+begin_src ks
  local hbt is bt(mnv:deltav:mag/2).
  local dt is mnv:eta - hbt.
#+end_src

BE CAREFUL: vessel is probably currently maintaining an
attitude that keeps batteries charged. Do not mess with
steering until 60 seconds before the burn, avoid trying
to steer into a V(0,0,0) deltav, ando handle the case
where the node goes away before someone else takes over
steering.

#+begin_src ks
  if dt < 60
    lock steering to
      choose mnv:deltav
      if hasnode and mnv:deltav:mag > 0
      else facing.
#+end_src

#+begin_src ks
  if dt <= 0 return mpinc().
#+end_src

The swadj function computes the warp factor right now
that would allow us to come to a halt at the given time.
But we DO need to call it frequently so it can lower the
warp factor in time!

#+begin_src ks
  swadj(dt-30). return 1/10. }). }.
#+end_src
