#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../Archive/simple.ks

simple.ks - a collection of common simple steps

* Import Required Packages

#+begin_src ks
  import("nv").
  import("fmt").
  import("time").
#+end_src

* Radar Altimeter Calibration

** radalt0 - value of alt:radar taken when in contact with surface.

#+begin_src ks
  set radalt0 to nvget(1,"radalt0",alt:radar).
#+end_src

** ra - LOCK evaluating to radar altitude (for this file only)

#+begin_src ks
  lock ra to alt:radar-radalt0.
#+end_src

** radcal(h) - calibrate the radar altimeter.

Construct a LOCK called RA that reads zero when the
radar altimeter ALT:RADAR reads H, which defaults to the
current ALT:RADAR value.

Call this with no parameters when resting on the ground.

Call this with a number determined when designing the
vessel when a lander is approaching a landing; the value
must be determined by deploying just the lander stage
and examining the ALT:RADAR value.

#+begin_src ks
  set radcal to { parameter h0 is alt:radar.
    set radalt0 to nvput(1,"radalt0",h0).}.
#+end_src

** mpradcal(h0) -- add mission plan step to calibrate LANDER radar.

The appropriate value of H0 is specific to the stage of
the vessel, and the value used in this call must be
determined when designing the vessel by capturing ALT:RADAR
with the lander sitting on a surface.

#+begin_src ks
  set mpradcal to { parameter h0. return mpone({radcal(h0).}).}.
#+end_src

* Mission Status String

This is probably a good string to put at the top
of a mission data display screen.

** mss - variable holding current mission status string

#+begin_src ks
  set mss to nvget(1,"status","KOSPLAN Initializing").
#+end_src

** putstat(m) - update mission status string

#+begin_src ks
  set putstat to { parameter m.
    set mss to nvput(1,"status",m). }.
#+end_src

** mpstat(m) - add step to set Mission Status String

#+begin_src ks
  set mpstat to { parameter m. return mpone({putstat(m).}).}.
#+end_src

* mpcount - add "display countdown" to mission plan.

#+begin_src ks
  set mpcount to { mpadd({
    local t is -met().
    local d is round(t).
    if d<=1 mpinc().
    if d<=5 hud(TEE()).
    return t-round(t-1)-1/50.}).} .
#+end_src

* mplaunch - add "launch to 50 meters" to mission plan.


#+begin_src ks
  set mplaunch to {
    mpone({radcal().}).
    mpone({t0put(0).}).
    mpstat("Ignition").
    mpadd({
      if ra>50 return mpinc().
      lock steering to facing.
      lock throttle to 1.
      if maxthrust>0 return 1/100.
      if stage:ready stage.
      return 1/100.}).}.
  .
#+end_src

* mpmeco - add "main engine cut-off" to mission plan.

#+begin_src ks
  set mpmeco to {mpadd({
    lock throttle to 0.
    lock steering to prograde.
    return mpinc().}).}.
#+end_src

* mpcoast - add "coast to space" to mission plan.

#+begin_src ks
  set mpcoast to {mpadd({
    if altitude>=body:atm:height or verticalspeed<0 return mpinc().
    lock throttle to 0. lock steering to prograde. return 1.}).}.
#+end_src

* mpcirc - simple circularization

This is the simplest circularization technique
that I have seen: burn as needed to keep the
current apoapsis a fixed time in the future.

It has a disadvantage: for vessels that have
lower thrust-to-mass ratios, the lead time
embedded in this code may be too short, and
it will give up when it passes apoapsis.

For such vessels, please use *mncirc* found
in the *mnpro* package instead.

#+begin_src ks
    set mpcirc to {
      mpadd({
        if periapsis>apoapsis-100 return mpinc().
        lock steering to prograde.
        lock throttle to max(0,min(1,(2-eta:apoapsis/10))) *
          max(1/100,min(1,1-vang(steering:vector,prograde:vector)/5)).
        return 1.}).
      mpone({ lock throttle to 0. lock steering to prograde.}).}.
#+end_src

* mppdab - orient vehicle to Point Down At Body

Step terminates when the vessel is within
a few degrees of the desired attitude.

NOTE: this uses whatever BODY is current at the time
that the step runs, not when the step is built.

#+begin_src ks
  set mppdab to { mpadd({
    lock throttle to 0.
    lock steering to lookdirup(vcrs(body:position,ship:velocity:orbit),-body:position).
    local fa is vang(facing:forevector,steering:forevector).
    local ua is vang(facing:upvector,steering:upvector).
    if fa<5 and ua<5 mpinc(). return 1. }).}.
#+end_src

* mppdas - orient vehicle to Point Down At Sun

Step terminates when the vessel is within
a few degrees of the desired attitude.

#+begin_src ks
  set mppdas to { mpadd({
    lock throttle to 0.
    lock steering to lookdirup(vcrs(sun:velocity:orbit,sun:position),-sun:position).
    local fa is vang(facing:forevector,steering:forevector).
    local ua is vang(facing:upvector,steering:upvector).
    if fa<5 and ua<5 mpinc(). return 1. }).}.
#+end_src

* Display Update.

#+begin_src ks

  set pr to { parameter u,w.
    if w<1 return "".
    return u:tostring:trim:padright(w):substring(0,w).}.
  set pl to { parameter u,w.
    if w<1 return "".
    return u:tostring:trim:padleft(w):substring(0,w).}.

  set openterm to {
    if career():candoactions
      core:part:getmodule("kOSProcessor"):
        doevent("Open Terminal").}.

  set pagenew to {
    openterm().
    set tw to terminal:width-1.
    clearscreen.
    for i in range(24) print pr(" ",tw-1).
  }.

  set pageupdate to {
    set tw to terminal:width-1.

    print pr(time:full,tw-1) at (0,0).

    print pr(TEE(),16) at (0,1).
    print pr(ship:name,tw-17) at (16,1).

    print pr(status,16) at (0,2).
    print pr(mss,tw-17) at (16,2).

    local ps is fmt(periapsis/1000,0,1).
    if periapsis<0 or ps:length>7 set ps to "***".
    local as is fmt(apoapsis/1000,0,1).
    if apoapsis<0 or as:length>7 set as to "***".

    print pr("",16) at (0,3).
    print pr(body:name,7) at (16,3).
    print pr(ps+"x"+as+" km",20) at (24,3).
    print pr(fmt(orbit:inclination,5,1)+"°", tw-45) at (44,3).
  }.

  pagenew().
  set pagetime to round(time:seconds).
  when pagetime<=time:seconds then {
    set pagetime to round(time:seconds + 1)+1/50.
    pageupdate(). return not abort. }
#+end_src

