#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../Archive/simple.ks

- start bringing back "correct circular orbit"
  now called mpcirchere, keeping the
  mpsimplecirc that uses eta:apoapsis.
- allow mpsimpecirc to be tuned by the caller

simple.ks - a collection of common simple steps

* Import Required Packages

#+begin_src ks
  import("agl").
  import("bt").
  import("fmt").
  import("mp").
  import("nv").
  import("logger").
  import("time").
#+end_src

* Status Log File

#+begin_src ks
  local sl is mklogger("status").
#+end_src

* Mission Status String

This is probably a good string to put at the top
of a mission data display screen.

** mss - variable holding current mission status string

#+begin_src ks
  set mss to nvget(1,"status","KOSPLAN Initializing").
#+end_src

** putstat(m) - update mission status string

#+begin_src ks
  set putstat to { parameter m.
    if mss = m return. sl(m). set mss to nvput(1,"status",m). }.
#+end_src

** mpstat(m) - add step to set Mission Status String

#+begin_src ks
  set mpstat to { parameter m. return mpone({putstat(m).}).}.
#+end_src

* mpcount - add "display countdown" to mission plan.

#+begin_src ks
  set mpcount to { mpadd({
    local t is -met().
    local d is round(t).
    if d<=1 mpinc().
    if d<=5 hud(TEE()).
    return t-round(t-1)-1/50.}).} .
#+end_src

* mplaunch - add "launch to 50 meters" to mission plan.

#+begin_src ks
  set mplaunch to {
    mpone({t0put(0).}).
    mpstat("Ignition").
    mpadd({
      if agl()>50 return mpinc().
      lock steering to facing.
      lock throttle to 1.
      if availablethrust>0 return 1/100.
      if stage:ready stage.
      return 1/100.}).}.
  .
#+end_src

* mpmeco - add "main engine cut-off" to mission plan.

#+begin_src ks
  set mpmeco to {mpadd({
    lock throttle to 0.
    lock steering to prograde.
    return mpinc().}).}.
#+end_src

* mpcoast - add "coast to space" to mission plan.

#+begin_src ks
  set mpcoast to {mpadd({
    if altitude>=body:atm:height or verticalspeed<0 return mpinc().
    lock throttle to 0. lock steering to prograde. return 1.}).}.
#+end_src

* mpsimplecirc - add step to perform simple circularization

This is the simplest circularization technique
that I have seen: burn as needed to keep the
current apoapsis a fixed time in the future.

The optional parameter is the eta:apoapsis
at which the throttle will be set to full;
the strategy is to linearly ramp throttle
up to full starting at double that time.

#+begin_src ks
  set mpsimplecirc to { parameter lead is 10.
    mpadd({
      if periapsis>apoapsis-100 return mpinc().
      lock steering to prograde.
      lock throttle to max(0,min(1,(2-eta:apoapsis/lead))) *
        max(1/100,min(1,1-vang(steering:vector,prograde:vector)/5)).
      return 1.}).
    mpone({ lock throttle to 0. lock steering to prograde.}).}.
#+end_src

* mpcirchere - add step to correct orbit to circular

Compute the velocity we would currently have if we were in a circular
orbit, and burn as needed to correct our velocity.

#+begin_src ks
  set mpcirchere to {
    mpadd({
      if apoapsis-periapsis<100 or verticalspeed<=0 return mpinc().
      local vc is sqrt(body:mu/body:position:mag).
      local dv is vxcl(body:position,velocity:orbit):normalized * vc - velocity:orbit.
      if dv:mag < 1 return mpinc().
      local hbt is bt(dv:mag/2).
      if hbt < 1/10 return mpinc().
      local ttb is eta:apoapsis - hbt.
      if ttb < 1/10 return mpinc().
      return limit(0,5,ttb). }).
    mpadd({
      if apoapsis-periapsis<100 return mpinc().
      lock mpch_vc to
        vxcl(body:position,velocity:orbit):normalized *
        sqrt(body:mu/body:position:mag).
      lock mpch_dv to mpch_vc - velocity:orbit.
      if mpch_dv:mag < 1 return mpinc().
      lock steering to lookdirup(mpch_dv, facing:topvector).
      if ship:availablethrust<=0 return 1/10.
      lock throttle to
        limit(0,1,sqrt(5*mpch_dv:mag*mass/ship:availablethrust)) *
        limit(0,1,2-vang(steering:vector,facing:vector)/5).
      return 1.}).
    mpone({
      lock throttle to 0. lock steering to prograde.}).}.
#+end_src

* mppdab - orient vehicle to Point Down At Body

Step terminates when the vessel is within
a few degrees of the desired attitude.

NOTE: this uses whatever BODY is current at the time
that the step runs, not when the step is built.

#+begin_src ks
  set mppdab to { mpadd({ lock throttle to 0. bays on. lights on.
    lock steering to lookdirup(vcrs(body:position,ship:velocity:orbit),-body:position).
    local fa is vang(facing:forevector,steering:forevector).
    local ua is vang(facing:upvector,steering:upvector).
    if fa<5 and ua<5 mpinc(). return 1. }).}.
#+end_src

* mppdas - orient vehicle to Point Down At Sun

Step terminates when the vessel is within
a few degrees of the desired attitude.

#+begin_src ks
  set mppdas to { mpadd({ lock throttle to 0. bays on. lights on.
    lock steering to lookdirup(vcrs(sun:velocity:orbit,sun:position),-sun:position).
    local fa is vang(facing:forevector,steering:forevector).
    local ua is vang(facing:upvector,steering:upvector).
    if fa<5 and ua<5 mpinc(). return 1. }).}.
#+end_src

* Display Update.

#+begin_src ks
  set pr to { parameter u,w.
    if w<1 return "".
    return u:tostring:trim:padright(w):substring(0,w).}.
#+end_src

#+begin_src ks
  set pl to { parameter u,w.
    if w<1 return "".
    return u:tostring:trim:padleft(w):substring(0,w).}.
#+end_src

#+begin_src ks
  set openterm to {
    if career():candoactions
      core:part:getmodule("kOSProcessor"):
        doevent("Open Terminal").}.
#+end_src

#+begin_src ks
  set pagenew to {
    openterm().
    set tw to terminal:width-1.
    clearscreen.
    for i in range(24) print pr(" ",tw-1).
  }.
#+end_src

#+begin_src ks
  set pageupdate to {
    set tw to terminal:width-1.
#+end_src

    > Year # Day ## ##:##:##
    > T-##:##:##      Vessel Name
    > STATUS          kosplan status message
    >                 BODY     PERIxAPO km    INCL°
    > T-##:##:##      PERIAPSIS/APOAPSIS/TRANSITION/PERIOD

#+begin_src ks
  print pr(time:full,tw-1) at (0,0).
  print pr(TEE(),16)+pr(ship:name,tw-17) at (0,1).
  print pr(status,16)+pr(mss,tw-17) at (0,2).
#+end_src

#+begin_src ks
  local ps is fmt(periapsis/1000,0,1).
  if periapsis<0 or ps:length>7 set ps to "***".
  local as is fmt(apoapsis/1000,0,1).
  if apoapsis<0 or as:length>7 set as to "***".
#+end_src

#+begin_src ks
  print "  "+pr(body:name,14)+
    pr(ps+"x"+as+" km",20)+
    pr(fmt(orbit:inclination,5,1)+"°", tw-45) at (0,3).
#+end_src

#+begin_src ks
  local l4t is -1.
  local l4s is "".
#+end_src

#+begin_src ks
  if orbit:eccentricity<1 {
    local eee is round(orbit:period).
    if (l4t<0 or l4t>eee) {
      local l4t is eee.
      local l4s is "Period".}}
#+end_src

#+begin_src ks
  if eta:periapsis>0 {
    local eee is round(eta:periapsis).
    if (l4t<0 or l4t>eee) {
      set l4t to eee.
      set l4s to "Periapsis".}}
#+end_src

#+begin_src ks
  if apoapsis>0 {
    set eee to round(eta:apoapsis).
    if (l4t<0 or l4t>eee) {
      set l4t to eee.
      set l4s to "Apoapsis".}}
#+end_src

#+begin_src ks
  if orbit:hasnextpatch {
    set eee to round(eta:transition).
    if (l4t<0 or l4t>eee) {
      set l4t to eee.
      set l4s to "Transition".}}
#+end_src

#+begin_src ks
  if hasnode {
    set l4t to round(nextnode:eta).
    set l4s to "Maneuver".}
#+end_src

#+begin_src ks
  set l4s to (choose "since " if l4t<0 else "to ") + l4s.
#+end_src

#+begin_src ks
  if status="SPLASHED" or status="LANDED" or status="PRELAUNCH"
    print pr(" ",tw-1) at (0,4).
  else
    print "  "+pr(ydhms(abs(l4t)),14)+ pr(l4s,tw-17) at (0,4).
#+end_src

#+begin_src ks
  set lls to "lat: "+fmt(latitude,8,3)+"  lon: "+fmt(longitude,8,3).
  if altitude > 100000 set lls to "".
  print pr(lls,tw-1) at (0,5).
#+end_src

#+begin_src ks
  }.
#+end_src

#+begin_src ks
  pagenew().
  set pagetime to round(time:seconds).
  when pagetime<=time:seconds then {
    set pagetime to round(time:seconds + 1)+1/50.
    pageupdate(). return not abort. }
#+end_src

