#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../Archive/xfer.ks

xfer.ks - plan transfer to to a moon

The ship and the destination are in orbit
around the same body.

* Import Required Packages

#+begin_src ks
  import("mp").
  import("mn").
  import("math").
  import("hud").
  // import("fmt").
#+end_src

* gpl: Get Periapsis List for nextnode.

#+begin_src ks
  set gpl to {
    local l is list(). if not hasnode return l.
    local o is nextnode:orbit.
    until false {
      l:add(o:periapsis).
      if not o:hasnextpatch return l.
    set o to o:nextpatch. }}.
#+end_src

* mpxfer(body): plan (and execute) a free-return transfer to the named body.

#+begin_src ks
    set mpxfer to { parameter target_name. mpadd({
#+end_src

** set configuration information

#+begin_src ks
  local dest is body(target_name).
  HUD("Planning transfer to "+dest:name).
  local mu is body:mu.
  local target_flyby_altitude is 45000.
  local return_altitude is 45000.
  local planned_beyond is dest:soiradius / 2.
#+end_src

** Set up a maneuver node at an arbitrary time.

#+begin_src ks
  local t1_min is time:seconds + 300.
  local t1 is t1_min + 300.
  local t2 is t1.
  mnclr().
  local mnv is node(t1, 0, 0, 0). add mnv. wait 0.
#+end_src

*** xapo: adjust the apoapsis of the transfer.

The job of this function is to IMPROVE the apoapsis of the
transfer orbit based on looking at the state of the ship
at the starting time and of the body at the end.

If the orbits are not circular, then the body and dest
state information changes each time we change the
transfer orbit start time or transfer time.

#+begin_src ks
  local xapo is { parameter beyond.
#+end_src

**** update starting and ending radius using t1 and t2.

after updating t2, of course.

#+begin_src ks
  set t2 to time:seconds + mnv:orbit:eta:apoapsis.
  local curr_r is posat(t1, ship):mag.
  local new_rmax is posat(t2, dest):mag + beyond.
#+end_src

Grab the rmin and rmax of the existing transfer for
use in the visviva equations.

#+begin_src ks
  local old_rmin is mnv:orbit:periapsis + mnv:orbit:body:radius.
  local old_rmax is mnv:orbit:apoapsis + mnv:orbit:body:radius.
#+end_src

Use visviva to determine the speed along the transfer
as it was, and the speed along the transfer that gets
us out to the new rmax.

#+begin_src ks
  local v1 is vv(curr_r, old_rmin, old_rmax, mu).
  local v2 is vv(curr_r, old_rmin, new_rmax, mu).
#+end_src

Update the maneuver node. Be sure to wait for a phys tick
so that the derived data in mnv are updated.

#+begin_src ks
  set mnv:prograde to mnv:prograde + v2 - v1. wait 0. }.
#+end_src

The above process converges really quickly for MUN, but it
might be necessary to review this bit for transfers where
the starting and ending orbits are not quite so circular.

During configuration, we selected how far BEYOND the
destination body we should place our apoapsis; this is
what gives us the free-return trajectory.

#+begin_src ks
  xapo(planned_beyond).
  xapo(planned_beyond).
#+end_src

*** Scan forward for the best intercept.

#+begin_src ks
  local first_est_time is nextnode:time.
  local first_est_dpro is nextnode:prograde.
  local ae is 0.
  local daedt is 0.
#+end_src

**** measure_daedt: get derivative of ae with respect to time

The angle error "ae" is the angle made by the destination,
the body at the center, and the ship, at time T2.

The value "daedt" is how much "ae" changes per second that
we move T2 forward in time.

This function returns true if burns at T1, and at T1
after it has been incremented, both have an intercept;
T1 is left pointing at the second time. If both were
found, "daedt" is updated with the change in AE.

#+begin_src ks
  local measure_daedt is {
    if mnv:orbit:hasnextpatch return false.
    local old_ae is vang(posat(t2, ship), posat(t2, dest)).
    set t1 to t1 + 1. set mnv:time to t1. wait 0.
    if mnv:orbit:hasnextpatch return false.
    set ae to vang(posat(t2, ship), posat(t2, dest)).
  set daedt to ae - old_ae. return true. }.
#+end_src

**** Scan forward until we get a daedt measure.

This skips forward by 1/36th of the orbit period,
so it might skip past an intercept if the window
for the intercept is narrow.

#+begin_src ks
  until measure_daedt() {
    set t1 to t1 + orbit:period/36.
  set mnv:time to t1. wait 0. }
#+end_src

**** Make things line up.

Adjust t1 to where we estimate that ae is minimized.

This is a pretty good starting point for the transfer orbit.

#+begin_src ks
  local dt is -ae / daedt.
  set t1 to t1 + dt.
  until t1 > t1_min
    set t1 to t1 + 1/(1/orbit:period + 1/dest:orbit:period).

  set mnv:time to t1. wait 0.
#+end_src

**** fix_aero_using_prograde: adjust PROGRADE burn to tune AEROBRAKING altitude

This function, when called, observes the periapsis of
the orbit patch representing our return to the central
body, as a small change is made to the PROGRADE
component of the maneuver node. It then adjusts PROGRADE
to improve AERO altitude.

It repeats this process until the periapsis over the
return body is within acceptable bounds.

It has been observed that the effect this has on the
periapsis over the destination is small enough that
we can run this adjustment until it converges then
go back to adjusting the other.

#+begin_src ks
  local fix_aero_using_prograde is {
#+end_src

***** Configure the process.

#+begin_src ks
  local pstep is 1/100.
  local hr is return_altitude.
  local hm is hr - 1000.
  local hp is hr + 1000.
  local good_dpro is mnv:prograde.
#+end_src

Loop until done, of course.

#+begin_src ks
  until false {
#+end_src

Grab the periapse values of all orbit patches
from the maneuver node. If the result of the
maneuver does not have enough patches, then
terminate this process so we can try another
starting time.

#+begin_src ks
  local pl is gpl(). if pl:length < 3 {     // print ("warning: lost encounter while trying to fix aero [1].").
  set mnv:prograde to good_dpro. wait 0. break. }
#+end_src

Update our record of a "good" prograde burn value.
If our goal is met, we are done.
Otherwise, change prograde by a small amount.

#+begin_src ks
  set good_dpro to mnv:prograde.
  local h1 to pl[2].
  if hm <= h1 and h1 <= hp break.
  set mnv:prograde to mnv:prograde + pstep. wait 0.
#+end_src

Grab the periapse values of all orbit patches from the
maneuver node agaikn. If the result of the maneuver does
not have enough patches, then terminate this process so
we can try another starting time.

Compute the change in periapsis per unit of prograde
burn applied, then estimate the prograde burn that will
achieve the best value in our goal region.

Update the maneuver node and loop back.

#+begin_src ks
  local pl is gpl(). if pl:length < 3 {     // print("warning: lost encounter while trying to fix aero [2].").
  set mnv:prograde to good_dpro. wait 0. break. }

  local h2 is pl[2].
  local peri_per_dpro is (h2 - h1) / pstep.
  local adj_dpro to (hr - h2) / peri_per_dpro.
  set mnv:prograde to mnv:prograde + adj_dpro. wait 0. }}.
#+end_src

**** fix_flyby_using_time: adjust START TIME to tune MUN PERIAPSIS.

This function, when called, triggers the above method
to pull the return altitude to within range.

It then observes the periapsis of the orbit patch
representing our fly-by of the destination, as a small
change is made to the SCHEDULED TIME component of the
maneuver node. It then adjusts SCHEDULED TIME to try to
improve the fly-by altitude.

It repeates this whole process until the fly-by altitude
is within bounds.

It has been observed that the effect this has on the
aerobraking altitude is small enough that we can
converge by adjusting them alternately.

#+begin_src ks
  local fix_flyby_using_time is {
#+end_src

Configuration values.

#+begin_src ks
  local tstep is 1/1000.
  local hr is target_flyby_altitude.
  local hm is hr - 1000.
  local hp is hr + 1000.
  local good_time is mnv:time.
#+end_src

Loop until done.

#+begin_src ks
  until false {
#+end_src

Before messing with scheduled time, stabilize
our prograde burn to try to get to the center
of the goal region for the aero capture.

#+begin_src ks
  fix_aero_using_prograde().
#+end_src

Grab the periapse values of all orbit patches
from the maneuver node. If the result of the
maneuver does not have enough patches, then
terminate this process.

#+begin_src ks
  local pl is gpl(). if pl:length < 3 {     // print("warning: lost encounter while trying to fix flyby [1].").
  set mnv:time to good_time. wait 0. break.}
#+end_src

Update our record of a "good" scheduld maneuver time.
If our goal is met, we are done.
Otherwise, change prograde by a small amount.

#+begin_src ks
  set good_time to mnv:time.
  local h1 to pl[1].
  if hm <= h1 and h1 <= hp break.
  set mnv:time to mnv:time + tstep. wait 0.
#+end_src

Grab the periapse values of all orbit patches from the
maneuver node again. If the result of the maneuver does
not have enough patches, then terminate this process.

#+begin_src ks
  local pl is gpl(). if pl:length < 3 {     // print("warning: lost encounter while trying to fix flyby [2].").
  set mnv:time to good_time. wait 0. break. }
#+end_src

Compute the change in periapsis per unit of scheduled
time delay applied, then estimate the scheduled time
that will achieve the best value in our goal region.

Stepping all the way risks losing our intercept, so
take smaller steps allowing us to track prograde
burn values that keep us in our goal windows.

Update the maneuver node and loop back.

#+begin_src ks
  local h2 is pl[1].
  local peri_per_time is (h2 - h1) / tstep.
  local adj_time to (hr - h2) / peri_per_time.

  // take small steps or we lose our intercept.
  set mnv:time to mnv:time + adj_time/10.
  wait 0. }}.
#+end_src

**** Call the fix function once.

This is sufficient.

There are a bunch of debug prints here that might be
useful if things are going wrong.

#+begin_src ks
  fix_flyby_using_time().

  // local final_est_time is nextnode:time.
  // local final_est_dpro is nextnode:prograde.
  // print "final node: at "+ydhms(final_est_time)+", burn prograde "+fmt(final_est_dpro,0,2)+" m/s.".
  // local delta_est_time is final_est_time - first_est_time.
  // local delta_est_dpro is final_est_dpro - first_est_dpro.
  // print "delta node: adjust by "+ydhms(delta_est_time)+", "+fmt(delta_est_dpro,0,2)+" m/s.".

  // make really sure the node is settled.
  return mpinc(1/50). }).
#+end_src

*** also add plan steps to wait, execute, and clean up.

#+begin_src ks
  mnwait().
  mnexec().
  mnfini().}.
#+end_src
