#!/bin/bash -
sscr="$0"
self=$(basename "$sscr" .sh)
sdir=$(cd "$(dirname "$sscr")"; env PWD= /bin/pwd)
cd "$sdir"

for cf in .link/*.craft
do
    bn=$(basename "$cf" .craft)
    sf=.link/"$bn".craft
    df="$bn".craft
    [ -f  "$sf" ] || continue
    if [ "$sf" -nt "$df" ]
    then
        cp -pf "$sf" "$df"
        ts VAB: "$bn"
    fi
done
