#+PROPERTY: header-args :results none
#+PROPERTY: header-args :tangle ../../Archive/home/004 Flappy Bird/go.ks

go.ks -- GO script for the Big Hopper

This script manages the flight of the Big Hopper, which is
fairly simple:

Verified on *20260621* booted from boot/local

* Import Required Packages

#+begin_src ks
  import("mp").
  import("airspeed").
#+end_src

* Provide a GO function.

This function is executed by IMPORT when it
finds nothing more specific for this mission.

#+begin_src ks
  set go to {
#+end_src

** Clear and set up takeoff.log

#+begin_src ks
  local lf is home:combine("takeoff.log").
  deletepath(lf).
  log "Alt,GS,VS" to lf.
#+end_src

** If the flight engineer activate SAS, unlock steering.

#+begin_src ks
  when SAS then{
    print "SAS activated. You have the stick.".
    unlock steering.
  return false. }
#+end_src

** Define Mission Phases

*** set the controls

#+begin_src ks
  mpone({
    BRAKES ON.
    set Ct to 1.
    lock throttle to Ct.
    lock steering to heading(90, 5, 0).
  }).
#+end_src

*** light the fires

#+begin_src ks
  mpadd({
    print "Activate engines to launch".
    return choose mpinc() if availablethrust>0 else 2.}).
#+end_src

*** release the brakes

Release the brakes when the engines have spooled
up to 50% or when we are moving at 2 m/s.

#+begin_src ks
  mpadd({ if ship:thrust>availablethrust/4 or groundspeed>2 return mpinc(). return 1/10. }).
  mpone({ BRAKES OFF. }).
#+end_src

*** pitch nose up at 60 m/s

Typical small business jets take off at 75 to 100 m/s
and have an ascent rate of about 20 m/s.

#+begin_src ks
  mpadd({ if groundspeed<60 return 1/10.
  lock steering to heading(90, 15, 0). return mpinc(). }).
#+end_src

*** hands off the controls until we get to 2000 m.

I will be making significant use of MECHJEB
to fly this thing.

#+begin_src ks
  mpadd({ if altitude>=2000 return mpinc().
    log round(alt:radar)+","+round(groundspeed,1)+","+round(verticalspeed,1) to lf.
  return 1/10.}).
#+end_src

*** set up and turn on the airspeed controller.

This step never advances. That way, if we reboot, we will
create and start using a new airspeed controller, and we
will start with running astest() to cycle the airspeed
through some test setpoints.

#+begin_src ks
  mpadd({
    asn(1/10,1/1000,1).
    astest().
  until abort { }}).
#+end_src

* Run the Mission, then End the Program.

#+begin_src ks
  mprun(). print "program terminated".}.
#+end_src

